project:
  type: website
  output-dir: _site
  preview:
    port: 4444
    navigate: false
  resources:
  - fonts

website:
  title: "PANK"
  page-footer:
    left: "[České priority](https://ceskepriority.cz) 2023<br />[![](https://i.creativecommons.org/l/by-nd/3.0/cz/80x15.png)](https://creativecommons.org/licenses/by-nd/3.0/cz/)"
    center: "[![](/images/logolink_eta.png)](https://starfos.tacr.cz/cs/project/TL05000330)"
    right: "Built with [Quarto](https://quarto.org), kód <a href=https://github.com/petrbouchal/pank-foolkit>na Githubu</a>"
  navbar:
    right:
      - text: "<button class = 'btn-top'>Průvodce prací s poznatky</button>"
        file: pruvodce/index.qmd
      - pripadove-studie/index.qmd
      - text: "Slovníček"
        file: slovnicek.qmd
      - text: "Doporučení"
        menu:
        - text: "Jak přemýšlet o práci s poznatky"
          file: teze-o-praci-s-poznatky.qmd
        - systemova-doporuceni.qmd
        - text: "Co číst a využívat"
          file: inspirace.qmd
      - pribeh-projektu.qmd
    logo: logo.png
  open-graph:
    locale: cs_CZ
  favicon: favicon.png
  repo-url: https://github.com/petrbouchal/pank-foolkit
  # repo-actions: [edit, issue]

format:
  html:
    filters:
    - pandoc-quotes.lua
    language:
      title-block-author-single: " "
    lang: cs
    toc-location: left
    theme:
      light: [cosmo.scss, styles.scss]
      # dark: [darkly, styles-dark.scss]
    toc: true





