project:
  type: website
  output-dir: _site
  preview:
    port: 4444
    navigate: false
  resources:
  - fonts

website:
  title: ""
  navbar:
    right:
      - text: "   "
      - text: "Průvodce prací s poznatky"
        file: pruvodce/index.qmd
        menu:
        - text: "Celý průvodce"
          file: pruvodce/index.qmd
        - text: "Jak spolupracovat v týmu"
          file: pruvodce/index.qmd#rizeni
        - text: "Jak získávat poznatky"
          file: pruvodce/index.qmd#ziskavani
        - text: "Jak s poznatky pracovat"
          file: pruvodce/index.qmd#metody
        - text: "Jak dostat svou práci do světa"
          file: pruvodce/index.qmd#vyuziti
      - text: "Doporučení"
        file: doporuceni/index.qmd
      - pripadove-studie/index.qmd
      - pribeh-projektu.qmd
    logo: logotype_blue.png
  site-url: pank-foolkit.netlify.app
  sidebar:
  - title: Průvodce
    id: pruvodce
    style: floating
    border: false
    contents:
    - text: "Celý průvodce"
      file: pruvodce/index.qmd
    - text: "Spolupráce v týmu"
      file: "pruvodce/list-rizeni.qmd"
    - text: "Jak získat data a poznatky"
      file: "pruvodce/list-ziskavani.qmd"
    - text: "Jak s poznatky pracovat"
      file: "pruvodce/list-metody.qmd"
    - text: "Jak dostat svou práci do světa"
      file: "pruvodce/list-vyuziti.qmd"
  - title: blah
  open-graph:
    locale: cs_CZ
  favicon: favicon.png
  page-footer:
    left: "[České priority](https://ceskepriority.cz) 2023<div class='img-license'>[![](https://i.creativecommons.org/l/by-nd/3.0/cz/80x15.png)](https://creativecommons.org/licenses/by-nd/3.0/cz/)</div>"
    center: "[![](/images/logolink_eta.png)](https://starfos.tacr.cz/cs/project/TL05000330)"
    right: "Built with [Quarto](https://quarto.org), kód <a href=https://github.com/petrbouchal/pank-foolkit>na Githubu</a>"
  repo-url: https://github.com/petrbouchal/pank-foolkit
  # repo-actions: [edit, issue]

format:
  html:
    title-prefix: "PANK"
    callout-icon: false
    callout-appearance: simple
    bibliography: citace/pank-citace.bib
    filters:
    - pandoc-quotes.lua
    language:
      title-block-author-single: " "
    lang: cs
    toc-location: left
    title-block-banner: false
    title-block-categories: false
    reference-location: margin
    citation-location: margin
    theme:
      light: [cosmo.scss, styles.scss]
      # dark: [darkly, styles-dark.scss]
    toc: true
    toc-expand: true
    anchor-sections: false
    link-external-icon: true
    link-external-newwindow: true





