project:
  type: website
  output-dir: _site
  preview:
    port: 4444
    navigate: false
  resources:
  - fonts
  - nastroje

website:
  site-url: https://pank.cz
  image: /images/opengraph.jpg
  title: "PANK"
  navbar:
    title: false
    toggle-position: right
    right:
      - text: "   "
      - text: "Průvodce prací s poznatky"
        file: pruvodce/index.qmd
        menu:
        - text: "Celý průvodce"
          file: pruvodce/index.qmd
        - text: "Jak spolupracovat v týmu"
          file: pruvodce/index.qmd#rizeni
        - text: "Jak získávat poznatky"
          file: pruvodce/index.qmd#ziskavani
        - text: "Jak s poznatky pracovat"
          file: pruvodce/index.qmd#metody
        - text: "Jak dostat svou práci do světa"
          file: pruvodce/index.qmd#vyuziti
      - text: "Doporučení"
        file: doporuceni/index.qmd
      - pripadove-studie/index.qmd
      - pribeh-projektu.qmd
    logo: /images/logotype_blue.png
  twitter-card:
    image: /images/opengraph.jpg
    title: "PANK: Průvodce prací s poznatky"
    description: "I Váš tým potřebuje pracovat s poznatky. Inspirativní průvodce s návody, tipy a triky a zdroji pro Vás."
  open-graph:
    image: /images/opengraph.jpg
    title: "PANK: Průvodce prací s poznatky"
    description: "I Váš tým potřebuje pracovat s poznatky. Inspirativní průvodce s návody, tipy a triky a zdroji pro Vás."
    locale: cs_CZ
  favicon: favicon.png
  page-footer:
    left: "[České priority](https://ceskepriority.cz) 2023<div class='img-license'>[![](https://i.creativecommons.org/l/by-nd/3.0/cz/80x15.png)](https://creativecommons.org/licenses/by-nd/3.0/cz/)</div>"
    center: "[![](/images/logolink_eta.png)](https://starfos.tacr.cz/cs/project/TL05000330)"
    right: "Built with [Quarto](https://quarto.org), kód <a href=https://github.com/petrbouchal/pank-foolkit>na Githubu</a>"
  repo-url: https://github.com/petrbouchal/pank-foolkit
  # repo-actions: [edit, issue]
  search:
    # show-item-context: tree
    keyboard-shortcut: none
    type: overlay

format:
  html:
    title-prefix: "PANK"
    callout-icon: false
    callout-appearance: simple
    bibliography: citace/pank-citace.bib
    quarto-required: ">= 1.3.450"
    filters:
    - pandoc-quotes.lua
    language:
      title-block-author-single: " "
      related-formats-title: "Ke stažení"
    lang: cs
    toc-location: left
    title-block-banner: false
    title-block-categories: false
    reference-location: margin
    citation-location: document
    theme:
      light: [styles/cosmo.scss, styles/styles.scss]
    toc: true
    toc-expand: true
    anchor-sections: false
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: "^(?:http:|https:)\/\/(((www\\.)?pank\\.cz)|([a-z0-9\\-]*\\-\\-)?pank\\-cz\\.netlify\\.app?)"
    include-in-header: 
      file: "matomo.html"    





