project:
  type: website
  preview:
    port: 4444
    navigate: false

website:
  title: "PANK!!!"
  page-footer: "<br />České priority 2023, CC-BY-ND, Podpořeno <a href=\"https://tacr.cz\">TA ČR v programu Éta</a>"
  navbar:
    left:
      - pruvodce/index.qmd
      - pripadove-studie/index.qmd
      - teze-o-praci-s-poznatky.qmd
      - systemova-doporuceni.qmd
      - dalsi-zdroje.qmd
      - slovnicek.qmd
      - pribeh-projektu.qmd

format:
  html:
    language:
      title-block-author-single: "Otestováno?"
    lang: cs
    theme:
      light: [cosmo, styles.scss]
      # dark: [darkly, styles-dark.scss]
    toc: true




