project:
  type: website
  preview:
    port: 4444
    navigate: false
  resources:
  - fonts

website:
  title: "PANK [draft]"
  page-footer:
    left: "České priority 2023<br />CC-BY-ND, Podpořeno <a href=\"https://tacr.cz\">TA ČR v programu Éta</a>."
    right: "Built with Quarto, kód <a href=https://github.com/petrbouchal/pank-foolkit>na Githubu</a>"
  navbar:
    right:
      - pruvodce/index.qmd
      - text: "|||"
      - pripadove-studie/index.qmd
      - teze-o-praci-s-poznatky.qmd
      - systemova-doporuceni.qmd
      - slovnicek.qmd
      - inspirace.qmd
      - pribeh-projektu.qmd
  open-graph:
    locale: cs_CZ
  favicon: favicon.png
  repo-url: https://github.com/petrbouchal/pank-foolkit
  # repo-actions: [edit, issue]

format:
  html:
    language:
      title-block-author-single: " "
    lang: cs
    theme:
      light: [cosmo.scss, styles.scss]
      # dark: [darkly, styles-dark.scss]
    toc: true





