---
pagetitle: "PANK"
title-block-banner: false
toc: false
listing: 
  - id: tym
    type: grid
    template: ejs/tym.ejs
    contents: tym.yaml
---

:::{.column-page-inset}

<br />

::: {.grid}

::: {.g-col-12 .g-col-md-6}

Tady obrázek

:::

::: {.g-col-12 .g-col-md-6}


### Pracovat s poznatky* potřebuje i Váš tým.<br />

<br />

:::{.btn .btn-primary}
[Průvodce prací s poznatky](/pruvodce)
:::

<br />

\* *poznatky*: analýzy, data, podklady, nebo taky angl. *evidence*

<br />

:::
:::

:::{.page-full .strip .page-inset}

:::{.aside}

<br />

:::

:::{.grid}


:::{.g-col-12 .g-col-md-6}


### Co v průvodci najdete?

:::{.front-listing-left}

- **návody, postupy a zlepšováky**
- vyvinuté spolu s týmy v české státní správě.
- řeší **reálné problémy a situace**
- vychází ze současné mezinárodní **praxe a odborné literatury**.
:::

:::
:::{.g-col-12 .g-col-md-6}

### Chcete se rovnou začíst?

:::{.front-listing-right}


- [Jak začít](/pruvodce/jak-zacit)  
- [Jak spolupracovat v týmu](/pruvodce/list-rizeni.html) 
- [Jak získávat poznatky](/pruvodce/list-ziskavani.html)   
- [Jak s poznatky pracovat](/pruvodce/list-metody.html)   
- [Jak svou práci dostat do světa](/pruvodce/list-vyuziti.html) 

:::

<br />

:::
:::

:::

:::{.grid}

:::{.g-col-12 .g-col-md-6}

<br />

Obrázek
:::


:::{.g-col-12 .g-col-md-6}


## Vycházíme z praxe týmů ve státní správě

Návody a postupy jsme vyvíjeli a testovali ve spolupráce se šesti týmy v několika organizacích.   Zkušenosti z práce s těmito týmy jsme zachytili v případových studiích.  
Najdete v nich **příběhy** o tom, co se nám v týmech dařilo a nedařilo měnit, a také **dobré praxe**, na které jsme narazili.

:::{.btn .btn-primary}
[Číst případové studie ⟶](/pripadove-studie)
:::

<br />

:::

:::

:::

:::{.page-full .strip .page-inset}

:::{.aside}
<br />
:::

## Naše doporučení

Místo "data" a "evidence" jsme si zvykli mluvit o *práci s poznatky*. Co byste o práci s poznatky měli vědět, než se pustíte do snah o její zlepšování?

:::{.btn .btn-primary}
[Co jsme se za dva roky dověděli o práci s poznatky ⟶](/teze-tymy)
:::

<br />

Ne všechno změníte sami tím, že budete pracovat na svém týmu. Některé překážky kvalitní práce s poznatky mají kořeny v zákonech, pravidlech, organizačním fungování úřadů.

:::{.btn .btn-primary}
[Co doporučujeme změnit na úrovni státu a zákonů ⟶](/doporuceni)
:::

<br />

:::

<br />

## Náš tým podporuje informované rozhodování ve veřejné správě

Jsme tým složený hlavně z výzkumníků z [Českých priorit](https://ceskepriority.cz).

Rádi Vám pomůžeme při využití některého z [návodů v průvodci](/pruvodce) nebo s Vámi prodiskutujeme naše [doporučení](/doporuceni).

:::{.btn .btn-primary}
[Ozvěte se nám ⟶](mailto:email@ceskepriority.cz)
:::


<br />


:::{.d-none .d-sm-block}
:::{#tym}
:::
:::


V odborném poradním týmu nám pomáhala řada expertů z řad praktiků a akademiků a těžili jsme také z rad mnoha mezinárodních odborníků.

Kromě rozvoje analytické práce se České priority zaměřují na systémové změny v oblasti informovaného rozhodování. Pomáháme také rozvíjet foresight, forecasting a aplikace metod analýzy přínosů a nákladů.

:::{.btn .btn-primary}
[Více o Českých prioritách ⟶](https://ceskepriority.cz)
:::

<br />

Tento průvodce a všechny související výstupy vznikly díky Technologické agentuře ČR, která podpořila náš projekt PANK. 

:::{.btn .btn-primary}
[Příběh projektu ⟶](/pribeh-projektu)
:::



