---
title: "Agentura pro sociální začleňování"
subtitle: "Případová studie"
tagline: "**Oddělení výzkumu a evaluací Agentury pro sociální začleňování**, přináší poznatky do rozhodování o sociálním začleňování na lokální i centrální úrovni."
zkratka: ASZ
description: "Výzkum a evaluace pro sociální začleňování"
aliases: 
  - asz
listable: "listable"
---

Tato případová studie shrnuje vývoj spolupráce s oddělení výzkumů a evaluací (dále OVE) na Odboru (agentuře) pro sociální začleňování na MMR. Zaměstnanci tohoto oddělení realizují výzkumnou práci v obcích, které spolupracují s MMR na tvorbě lokálních strategiích sociálního začleňování. V tomto ohledu se jedná o čistě analytický útvar, který sbírá data a vytváří podklady pro tvorbu lokálních strategií, návrhy opatření a jejich následná evaluace. Hlavním těžištěm práce historicky spočívalo ve sběru kvalitativních dat skrz rozhovory a pozorování, ale v posledních letech se vyvíjí snahy o jejich doplnění a rozšíření pomocí kvantitativních dat. Spolupráce s tímto týmem se tedy zaměřila převážně na oblast kvantitativních dat, jelikož pro aplikaci kvalitativních metod již disponuje tento tým pokročilým know-how. 

#Proč se tým zapojil do projektu 
Vedení a členové týmu se plně ztotožňují s myšlenkou evidence-based přístupů při tvorbě veřejných politik v oblasti sociálního začleňování. Ty nicméně mnohdy naráží na politické motivace a zájmy lokálních zastupitelů, a proto mají kvalitativní i kvantitativní poznatky z terénu hrát stěžejnější roli při vyjednávání s lokálními zastupiteli. Zvýšení jejich kvality, ale i srozumitelnosti a využitelnosti dalšími aktéry tudíž bylo hlavní motivací, proč se zapojit do projektu PANK. 

Paralelně se ale toto oddělení potýká s interními a organizačními překážkami. Jednak jsou všechny aktivity projektového charakteru, což neumožňuje dlouhodobý rozvoj dovedností v týmu v důsledku fluktuace a omezených časových možností. Z hlediska mixu dovedností je tým převážně zaměřený na aplikaci kvalitativních (antropologických) metod a pouze jeden člen je zaměstnán výhradně s datově analytickou rolí. Ostatní členové disponují základními dovednostmi v analýze dat, ale v důsledku časového vytížení je prostor pro jejich rozvoj velmi omezený. Rozšířit “datovou gramotnost” celého týmu tak byla druhou motivací vedení týmu. 

# Představení týmu

Odbor (Agentura) pro sociální začleňování (dále jen ASZ) na MMR je hlavním expertním nástrojem Vlády ČR pro podporu sociálního začleňování. Po zahájení spolupráce došlo k systemizaci na MMR, kdy tento odbor byl přesunut ze sekce Bydlení, výstavby a veřejného investování do současné sekce Bydlení a sociálního začleňování. Oddělení výzkumů a evaluace je hlavní realizátorem analytických aktivit monitorování sociálního vyloučení na celostátní úrovni (tvorba a údržba Indexu sociálního vyloučení, realizace tematicko-průřezových studií v dílčích oblastech sociálního vyloučení), tvorba analytických vstupů pro strategické materiály ASZ, definování a sledování potřeb obyvatel sociálně vyloučených lokalit (vstupní analýzy v obcích a návrhy doporučení v oblasti sociálního začleňování) a evaluace činností ASZ. Celkem je v oddělení přibližně 40 výzkumníků. 

OVE vytváří tyto analytické materiály díky kompilaci kvalitativních i kvantitativních dat. Kvantitativní data využívají výzkumníci deskriptivně pro popis stavu sociálního vyloučení v dané lokalitě (např. podíly osob v exekucích, počty odběratelů dávek, atp). Jedná se zejména o administrativní data od různých poskytovatelů (mj. ČSÚ, MPSV, MŠMT, Policie ČR, Exekutorská komora…), do menší míry sbírá ASZ vlastní data skrz dotazníková šetření. Pro hlubší poznání v terénu jsou využívány kvalitativní metody rozhovorů (příp. fokusní skupiny) a pozorování. Díky těmto poznatkům dokáží zachytit subjektivní vnímání aktérů v lokalitách, ať se jedná přímo o sociálně vyloučené osoby nebo o sociální pracovníky a lokální úředníky či zastupitelé. Souhrn těchto poznatků tvoří různé analytické podklady (např. vstupní a situační analýzy, tematické analýzy), které jsou využívány různými aktéry jak uvnitř, tak vně ASZ. Uvnitř ASZ jsou hlavními adresáty lokální koordinátoři a lokální experti, kteří působí dlouhodobě v zapojených lokalitách a jednají přímo s lokálními úřady, regionální centra a centrální vedení v Praze. Hlavními uživateli výstupů mimo ASZ jsou zástupci samospráv (zastupitelé a úředníci), kteří navrhují a implementují doporučená opatření, dále představitelé neziskových organizací a sociálních služeb. Lze též předpokládát, že výstupy jsou využívány i akademickými výzkumníky.

Vedle oddělení výzkumů a evaluací jsou v ASZ ještě dva útvary, které vykonávají analytickou činnost. Jedním bylo oddělení strategické a odborné podpory (který po poslední systemizaci zanikl), jenž koordinovalo činnost expertních konzultantů. Ti spolupracovali s OVE při realizaci tematických analýzách se zaměřením na určitou oblast (např. vzdělávání, bydlení, oddlužení) a byli rovněž přítomni při vyjednávání se zastupitelstvi partnerských obcí. Druhý analytický útvar realizuje projekt “Projekt Agentura pro sociální začleňování jako inovační aktér politiky sociálního začleňování”, který podporuje inovativní přístupy při tvorbě veřejných politik zejména na krajské úrovni, organizuje semináře, workshop apod. pro celou partnerskou síť a pravidelně publikuje newsletter. 

Spolupráce s OVE proběhla v časovém období, kdy v souvislosti s termíny programového období ESF 2014-2020, končily dva stěžejní projekty. Jedním z nich byl “Inkluzivní a kvalitní vzdělávání v územích se SVL” (financováno z OP VVV), přičemž hlavní náplní práce OVE v období spolupráce byla tvorba evaluačních zpráv. Tento projekt nebyl prodloužen, a proto nebylo relevantní cílit intervence na aktivity realizované v něm. Druhý projekt, který rovněž ke konci roku 2022 končil, byl “Individuální projekt OPZ – Systémové zajištění sociálního začleňování”. Opět se činnosti OVE soustředily převážně na evaluace a prostor pro aplikaci různých intervencí tak byl omezen. Nicméně na tento projekt navazuje další projekt financovaný z OPZ+ s názvem “Rozvoj systémů pro sociální začleňování”. Kvůli nejistotám ohledně parametrů navazujícího projektu bylo nutné vyčkat na jeho oficiální zahájení a zároveň došlo v rámci odboru pro sociální začleňování k interní reorganizaci, zejména odchod předchozího ředitele (pan Beňák) a tranziční období před nástupem nového (pan Šimáček). Tyto skutečnosti částečně omezily možnosti spolupráce, jelikož panovala nejistota ohledně náplni aktivit týmu OVE, přičemž nebylo ani jisté, kolik členů by bylo zaměstnáno i na další projekt. 

# Průběh spolupráce v PANK

## Diagnostická fáze

Cílem diagnostické fáze bylo nejprvé pochopení obsahu a způsob fungování práce s poznatky v OVE. Vedlejším cílem bylo sbírat podněty a doporučení od členů týmu ohledně způsobů, zlepčit práci s poznatky. Tuto fázi jsme zakončili prioritizací podnětů pro aplikaci intervencí. 

Během diagnostické fáze byly využity čtyři výzkumné metody: workshop, polostrukturované rozhovory, pozorování a analýza dokumentů (desk research). Úvodní workshop (10/12/2021), během kterého se představili členové týmu (7 přítomných), kteří následně popsali hlavní činnosti v jejich agendách a byly identifikované oblasti, v nichž vnímají největší potenciál pro rozvoj analytických kapacit. Následně proběhlo 7 polostrukturovaných rozhovorů s členy týmu a s vedoucí oddělení. Dotazy se soustředily na způsoby práce, vnímání překážek pro rozvoj analytických kapacit a úvahy o dílčích intervencích, které by mohly přispět pozitivním změnám ve fungování týmu. Následně byly na základě rozhovorů a desk-research zmapovány vstupní poznatky, výstupy a jejich příjemci (viz schéma níže). Posléze byli osloveni vybraní uživatelé těchto výstupů (3 rozhovory s lokálními koordinátory a metodičkou na regionálním centru).

Členové týmu OVE vnímají s cílem shodně, že jeho účelem je poskytovat empiricky podložené analýzy a data pro informované rozhodování v oblasti sociálního začleňování. Sdílí motivaci směrem k poskytnutí kvalitních analýz, které podporují procesy tvorby veřejných politik v této oblasti. S cílem zvýšit svůj přínos se také tým OVE ambiciózně snaží více se podílet na formulaci veřejných politik, a to prostřednictvím syntézy poznání a znalostí akumulovaných v posledních letech.

V rámci oddělení byly implementovány opatření, jako je tzv. buddy systém a stínování, která mají za cíl lépe připravovat nově příchozí zaměstnance. Tyto kroky jsou nezbytné vzhledem ke specifikům cílových skupin, citlivosti některých témat a dodržení etických zásad výzkumníků. Kromě toho jsou prostřednictvím pozic metodiků nastaveny procesy metodické podpory pro aplikaci výzkumných metod a interpretaci výsledků šetření. Původně se tyto procesy zaměřovaly především na kvalitativní metody, ale během posledních let byla podpora rozvíjena také v oblasti kvantitativních metod.

Nicméně, vývoj analytických aktivit čelí několika překážkám. Jednou z hlavních je nejasné vymezení rolí a činností OVE, jelikož jsou současně realizovány aktivity sběru empirických podkladů pro práci v lokalitách (vstupní analýzy) a kompilace obecnějších poznatků k tématu sociálního vyloučení (tematicko průřezové analýzy). Toto rozdělení není plně reflektováno v řízení týmu, což vytváří situaci, kdy se tým často snaží ad hoc přizpůsobovat potřebám. Výzkumné aktivity OVE jsou financovány z projektových fondů ESF. Tento model financování přináší s sebou určité výzvy, jelikož zavádí rigidní procesy projektového řízení, které mohou komplikovat realizaci výzkumných aktivit. Tlak na dodržení lhůt a generování různých výstupů často vede ke snížení hloubky a kvality analýz. Dále projektové financování přispívá k fluktuaci zaměstnanců, což může mít negativní dopad na kontinuitu a udržení znalostí v týmu.

Pokud jde o přístup k poznatkům a práci s nimi, OVE dlouhodobě sbírá a kompiluje administrativní data, na jejichž základě vytváří časové řady ve formě Indexu sociálního vyloučení. Tato databáze poskytuje nejucelenější soubor poznatků k tématu sociálního vyloučení, kterým státní správa disponuje. Tým OVE také vyvíjí úsilí o sdílení těchto poznatků a znalostí jak interně, tak pro vedení a veřejnost. Mechanismy pro sdílení informací a poznatků jsou důležité pro rozvoj tzv. institucionální paměti, která zahrnuje schopnost organizace efektivně zpracovávat interní know-how pro svůj další rozvoj. Díky těmto mechanismům lze signifikantně zkvalitnit a urychlit analytickou práci.

Nicméně, přestože existují procesy pro sdílení dat a poznatků, neexistují systematické postupy pro jejich ukládání a opětovné využití (knowledge management). To znamená, že vyhledání konkrétních analýz na webových stránkách OVE je nepřehledné i pro členy týmu, a podobně není snadná orientace ani v některých interních zdrojích. V minulosti se také opakovaně stalo, že pracovník, který opouští OVE, odnese část sesbíraných poznatků a tacitních znalostí, aniž by to bylo zaznamenáno (např. přepisy z rozhovorů, poznámky z terénu, popis metodického postupu, kontakty atd.).

Vzhledem k některým administrativním a statistickým omezením nemá tým OVE plný přístup ke všem datům, která by chtěl získat pro své analýzy. Některá data, jako např. mikrodata ze šetření SILC, jsou nedostupná, nebo je zdlouhavé získat určité datové sady v požadovaném formátu a detailnosti. Členové týmu také zaznamenali, že přístup k datům je často podmíněn osobními kontakty a sociálním kapitálem.

Pokud jde o analytické postupy a metody, tým OVE má dlouhodobě budované kapacity pro realizaci kvalitativních výzkumů ve specifickém kontextu sociálně vyloučených lokalit. Tým pracuje se zavedenými metodickými postupy pro realizaci výzkumů. Navíc si členové týmu občas vytvářejí metodické postupy a mají snahu je systematizovat. Vedení ASZ se zároveň snaží podporovat rozvoj přístupů mixed methods, tedy propojení kvalitativních a kvantitativních metod výzkumu. V současné době ale nejsou tyto postupy systematizovany a navíc je tým převážně tvořen výzkumníky s kvalitativním zaměřením. 

Tým OVE také zpracovává evaluace v závěrečných fázích projektů, ale z důvodu omezenosti dat a časových kapacit jsou tyto evaluace spíše zaměřeny na procesy a výsledky než na dopady navrhovaných opatření v lokalitách. Evaluace plní spíše formální účely (accountability), ale nejsou systematicky využívány pro učení se a rozvoj analytických kapacit na základě získaných poznatků.

Využitelnost výstupů týmu OVE je důležitým aspektem, který má vliv na přínos a efektivitu analytických prací. Členové týmu si jsou vědomi potřeby adaptovat a cílit komunikaci výstupů na různé skupiny uživatelů. Výstupy oddělení OVE mají potenciál být využity mnoha aktéry na lokální i národní úrovni, ale zatím chybí cílenější formy komunikace pro další relevantní aktéry, jako jsou policy makers na resortní úrovni, odborná veřejnost a akademici. V minulých letech členové týmu OVE naráželi na nedostatečnou spolupráci s oddělením pro vnější komunikaci, což omezilo efektivitu a účinnost komunikace výstupů.

Některé výstupy týmu, jako jsou vstupní analýzy a tematicko průřezové analýzy, jsou zpracovávány podle jednotného modelu, ale nedochází ke sjednocení grafických prvků a vizuální identity ASZ. To může snižovat srozumitelnost a zapamatovatelnost výstupů. Kromě toho chybí v některých výstupech manažerské shrnutí, které by umožnilo časově vytíženým aktérům rychle se seznámit s nejdůležitějšími poznatky a doporučeními. Dalším aspektem, který brání plnému využití výstupů, je omezení přístupu k určitým kvantitativním datům, která nejsou zveřejňována v režimu open data. To znemožňuje další využití těchto dat akademickou nebo odbornou veřejností. Není také vytvářena přehledová dokumentace o úspěšných opatřeních, která se osvědčila v konkrétních lokalitách, což by mohlo sloužit jako důležitý podklad pro rozhodování na základě dobrých praxí.

V návaznosti na závěry diagnostické fáze jsme navrhi intervence, které mají potenciál překonat výše uvedené překážky v práci s poznatky. Vycházeli jsme také z představ členů týmu a vedení ohledně směrů rozvoje, které pokrývaly široké spektrum činností. Mezi nimi patří například užší a systematická spolupráce s akademií a s ostatními složkami státu, využití širší škály metod a dovedností a profesionalizace komunikace výsledků výzkumu. Zároveň zazněly náměty ohledně zefektivnění práce s daty (data management) a jejich prezentace, dále ohledně využívání dotazníkových šetření. 

Během druhého workshopu jsme navrhli možných intervencí, které jsme s vedením členy týmu prioritizovali v souladu s kapacitami a plánovanou náplní práce v dalším odbobí. Navržené intervence pokrývaly tři oblasti: dopad na tvorbu veřejných politik, interní pracovní procesy v oblasti managementu dat a aplikaci mixed methods a způsoby prezentace výsledků výzkumu (zejména vizualizace dat). První oblast je poměrně široká a týká se i vnějších aktérů v ekosystému, zahrnuje zejména intervence směřující k tvorbě syntéz z předchozích výzkumů a doporučení na jejich základě. Tyto aktivity bohužel ale nejsou hlavním předmětem práce v OVE a nebylo by možné na ně alokovat dostatek času a interních kapacit (navíc tuto činnost částečně provádí vedlejší oddělení v rámci inovačního projektu). Proto jsme se rozhodli soustředit se na dvě ostatní oblasti týkající se interních procesů (design mixed methods a data management) a vnější komunikace (vizualizace dat). 
 
# Intervence

## Využití smíšených metod

Členové i vedení týmu vyjádřili ambice rozšiřovat paletu výzkumných nástrojů zejména ve vstupních a situačních analýzách. Kvalitativní šetření jsou tak stále více doplňována o analýzy administrativních dat a dotazníkovými šetření. Integrace kvalitativních a kvantitativních poznatků do výzkumného designu je poměrně složitá disciplína, která vyžaduje jednak adekvátní mix metodologických dovedností v týmu, ale také zavedené postupy pro sladění výzkumného designu s výzkumnou otázkou, pro interdisciplinární spolupráci a pro Quality Assurance. Paralelně jsme se věnovali i specifičtější oblasti sběru dat pomocí dotazníkových šetření a využití administrativních dat. Intervence tak měla za cíl společně nastavit interní procesy pro design mixed methods výzkumů, prezentace jejich výsledků a zavedení postupů pro Quality Assurance.

V první fázi této intervence bylo zapotřebí hlouběji analyzovat existující výzkumy, které využívaly mixed methods. Následně jsme společně s členy týmu identifikovali hlavní vnímané překážky pro jejich aplikaci. Z toho vyplynuly překážky a nedostatky, které se týkají dvou oblastí. První je nedostatečné zexplicitnění důvodů, proč během designu výzkumu mají být využity mixed methods. To se odráží i v samotných výstupech, kde výzkumný design byl popsán pouze zevrubně a nebyl tudíž transparentní a replikovatelný (zejména pro účely zajištění Quality assurance). Druhá oblast se týká konkrétně aplikace kvantitativních metod (ať jde o sběr dat skrz dotazníky nebo vytěžení administrativních dat), kde pro úspěšnou realizaci těchto výzkumů je nezbytné, aby všichni výzkumníci disponovali dovednostmi v obou přístupech. 

Pro rozhodování o výzkumném designu a jeho následný popis při prezentaci výsledků jsme vyšli z metodologické literatury ohledně mixed methods a připravili tzv. flowcharty, které mají usnadnit rozhodování týmu při designu a koordinaci mixed methods výzkumů. Ty mohou být využity jak interně pro snadnější koordinaci, tak jako součástí výstupu v zájmu transparentnosti. V rámci flowchartu jsou pro každý krok ve výzkumném designu označeny vstupy, postupy a výstupy (případně meziprodukty). Takový materiál se jeví jako užitečný zejména pro identifikaci potřebných datových zdrojů, ale také možných překážek při jejich využití. Umožní také zjednodušit rozhodovací procesy, jelikož je nejprvé nutné uvažovat o designu, který nejlépe odpovídá výzkumným otázkám. To je zejména důležité při vyjednávání s lokálními partnery, aby nedošlo k návrhu designu, který neodpovídá potřebám, ale také pro odůvodnění vybraného designu při prezentaci výsledků. 

V další fázi jsme se soustředili na aspekty týkající se využití kvantitativních metod. V oblasti tvorby dotazníkových šetření jsme identifikovali zejména potřebu zavést postupy pro tvorbu a operacionalizaci otázek. K tomu nebylo zapotřebí přímo aplikovat nové postupy, ale navrhli jsme okrajově změnit stávající skrz zapojení datového analytika v raných fázích jednání o designu výzkumu. Do té doby totiž vstupoval až v pozdějších fázích spíše s rolí připomínkovací. Navrhli jsme také více pilotovat dotazníky již v raných fázích pro zajištění jejich srozumitelnosti, čehož se právě může ujmout datový analytik. Sekundárně mohlo být přínosné také využít banku otázek, které jsou opakovaně využívané. Z diskusí s členy týmu ale vyplývalo, že by se týkala pouze omezeného množství otázek. Jelikož se v dalším období neplánovali výzkumy využívající dotazníková šetření, rozhodli jsme se zaměřit intervenci na využití administrativních metod, což popisujeme v další kapitole.  

## Data management

Zde bude popis intervence Data management

### Vizualizace dat

Mezi nedostatky, které identifikovali členové týmu během diagnostické fáze patří nesjednocené grafické formy datových výstupů. Při hlubší analýze těchto výstupů jsme nicméně konstatovali, že některé datové vizualizace trpí nedostatky z hlediska formy a obsahu. 

Kroky v intervenci:
Definovat skupiny uživatelů výstupů a jejich potřeb
Analýza výstupů - identifikovat dobré a špatné praxe
testování srozumitelnosti a čitelnosti datových vizualizací 
Vytvoření checklistu 

# Zobecnitelější vhledy

# Systémová doporučení

