---
title: "MŠMT: sekce vzdělávání a mládeže"
subtitle: "Odbory řízení a koordinace regionálního školství jsou jádrem vzdělávací politiky a analýz."
aliases: 
  - /msmt
  - /pripadove-studie/msmt
listable: "listable"
format: 
  docx: default
  html: default
---

Tato případová studie se od ostatních liší tím, jakou šíři od začátku projektu představuje.

Výzkumný tým navázal úzkou spolupráci se dvěma odbory ministerstva, kde jeden odbor je zaměřený na analytickou podporu a strategické řízení (O23 -- odbor vzdělávací politiky) a druhý je více implementační (O20 -- odbor řízení regionálního školství), ačkoliv má také své vlastní analytické kapacity a a tvoří a vyhodnocuje opatření v regionálním školství.

> MŠMT v projektu hrálo také roli aplikačního garanta.

## Představení týmu

Abychom porozuměli celému systému řízené regionálního školství na MŠMT, zapojili jsme také další dva věcné odbory (O21 a O22), především skrze rozhovory se vedoucími a referenty těchto odborů, které sice analytickou práci nevykonávají, ale jsou jejími uživateli. 

Tím jsme alespoň v diagnostické fázi pokryli většinu sekce vzdělávání a mládeže a i navazující intervence cílily na zlepšení fungování sekce jako celku, byť se přímo dotýkaly jen některých útvarů.    

Nejvíce jsme ale v projektu pracovali s týmem, který se staral o analyticko-koncepční podporu zbytku sekce ministerstva, jednalo se především o tři členy analyticko-koncepční oddělení. 
Jejich agenda byla velmi široká z povahy toho, že měli analyticky podporovat zbytek své sekce a řídit plnění strategických cílů ministerstva. Dále se také starali o běh externích výzkumů např. skrze veřejné zakázky v programu TA ČR BETA.  ​ 

## Diagnostika

Diagnostická fáze vycházela ze čtyř hlavních proudů poznání:

- Polostrukturované rozhovory
- Workshopy
- Desk research -- studium relevantních veřejněpolitických dokumentů a výstupů práce zapojených útvarů 
- Pozorování práce týmu vč. zúčastněného pozorování

Naše spolupráce začala vstupním workshopem, kde jsme se v online prostředí sešli s členy obou primárně zapojených odborů (O20 a O23). 
Účelem workshopu bylo představit projekt a jeho cíle a především získat názory na praxi práce s poznatky v obou odborech. 
V rámci workshopu jsme nechali všechny účastníky napsat, do připravené šablony na online platformě Jamboard, prostory pro zlepšení práce s poznatky. Z workshopu vyplynulo celkem 16 doporučení či přání. Těmi hlavními byly požadavky pro lepší sdílení dat, jak uvnitř, tak vně ministerstva, vytvoření databáze dostupného výzkumu a pravidelný přehled o tom, co, kdo dělá za práci.

Návazně na workshop proběhlo celkem 17 polostrukturovaných rozhovorů, především se členy spolupracujících odborů, ale také s dalšími aktéry na ministerstvu či v přidružených organizacích ministerstva (kancelář ministra, sekce zodpovědná za data a statistiky, Česká školní inspekce). V rozhovorech jsme se soustředili na způsoby práce, vnímání překážek pro realizaci a rozvoj analytických kapacit. Dále na úvahy o dílčích intervencích, které by mohly přispět pozitivním změnám ve fungování odborů.

Již během diagnostické fáze ovšem docházelo ke spolupráci s analyticko-koncepční oddělením, které chtělo pomoct s neodkladnými agendami. Mezi ně patřilo především zadávání výzkumu v rámci programu BETA2 spadajícího pod TA ČR a spolupráce na vytváření nového analytické útvaru na MŠMT.

Diagnostická fáze  ukázala konkrétní  prostory pro zlepšení:

- Nevyjasněnost rolí, kompetencí a agend vede k rozkolům a duplikacím či dokonce k vytváření návrhů politik, které jsou ve vzájemných rozporech.
- Vzájemná informovanost mezi odbory a odděleními je v mnoha oblastech nízká. To se týče, jak jednotlivých průběžných agend, tak datových zdrojů či dostupného výzkumu.
- Nositeli evidence-informed přístupu jsou jen někteří členové týmů. Personální změny tak silně ohrožují pokračování ve stejném duchu.
- Analytická práce není v mnoha případech delegována jako hlavní účel práce, ale stává se spíše sekundární po administrativní a organizační práci, která se stává hlavní náplní práce i analyticky smýšlejících lidí.
- Pracovní postupy nejsou systematicky sepsané, což může mimo jiné prodloužit adaptační proces při náboru nových zaměstnanců
- V některých případech chybí podpora vedení k evidence-informed přístupu.

Vzhledem k živému vývoji na ministerstvu -- připravoval se nový projekt zaměřený na rozvoj práce s daty -- jsme společně s analyticko-koncepčním oddělení dospěli k závěru, že nejlepší cesta adresovat většinu těchto témat bude skrze kvalitní nastavení nově vznikajícího analytického útvaru na ministerstvu. Hlavním důvodem bylo to, že na vzniku analytického útvaru pracovali zaměstnanci odboru 23. 

Tito zaměstnanci se také měli stát členy tohoto analytického útvaru a velkou část agend, které jsme chtěli v projektu adresovat, přenést sebou. Jinými slovy, vznik analytického útvaru byl v rámci projektu tak velký zásah, že veškerou spolupráci v práci s poznatky bylo vhodné řešit právě v souvislosti  se vznikajícím analytickým útvarem. 

## Intervence

Spolupráce řešitelského týmu s aktéry na MŠMT se soustředila do dvou intervencí, ty se ale promítly do většího počtu návodů v Průvodci analytickou prací.

:::{.aside}
**Odkazy na jednotlivé návody najdete u relevantních pasáží takto po straně.**
:::

### Zadávání výzkumu

Prvním řešeným tématem bylo zadávání externě řešených výzkumů (především externě přes TA ČR), ačkoliv jsme se s analyticko-koncepčním oddělením bavili o řešení celého procesu vedení výzkumu. Tedy od jeho zadání, přes jeho vedení až po řešení využití výstupu a jejich dohledatelné uložení (knowledge management).

:::{.aside}
Viz návod [Využití TAČR BETA ->](/pruvodce/beta2.qmd)
:::

Motivací k řešení bylo především snížit časovou zátěž, kterou celý proces obnášel, a zvýšit využitelnost a smysluplnost výzkumů. V první řadě jsme identifikovali dva problémy. Tím prvním bylo to, že věcná oddělení, jimž má výzkum pomáhat pro jejich rozhodování, často na začátku procesu nemají jasnou představu toho, co chtějí či mohou zkoumat. Tím druhým bylo to, že celý proces výzkumu obnášel nevyjasněnost rolí mezi jednotlivými stakeholdery.

První téma jsme řešili tak, že jsme společně vypracovali šablonu pro jednání s gestory výzkumu, tj. s těmi jednotlivci a útvary ministerstva, kteří by měli ze svého věcného pohledu benefitovat ze zodpovídání empirických otázek. Každá schůzka s potenciálním gestorem se měla držet této šablony tak, aby pro gestora bylo snadné si představit, co výzkum obnáší, co mu může přinést, ale také vyžaduje vyjasnění z jeho strany.

Šablona obsahuje následující:

> Představení od analytického oddělení
> 
> - Na úvod vysvětlení, proč jsme se sešli 
> - Vyjasnění jak výzkumný program probíhá a jaké jsou role v projektu
> 
> Otázky pro věcné útvary
> 
> - Čím se výzkumný projekt bude zabývat? Jaké otázky potřebujete mít zodpovězené? Jaké hypotézy byste se rádi pokusili potvrdit či vyvrátit?
> - Jak by měly vypadat výstupy projektu, abyste je dokázali co nejlépe využít?
> - Co může být překážka jejich využití?
> - Existují další aktéři, kteří by mohli tento výzkum využít?
> - Jaké jsou z Vašeho pohledu vstupy (jiné výzkumy a data, které máte k dispozici) 

Druhý problém jsme v návaznosti řešili pomocí jasně definovaných rolí v procesu zadávání a provádění výzkumů. Důležitým aspektem pro nás bylo nastavit role tak, aby se snížily nejasnosti a všichni zúčastnění stakeholdeři věděli co je od nich v rámci výzkumu očekáváno.

V tomto smyslu pro nás bylo stěžejní především zapojovat do procesu ty aktéry, kteří mají nakonec výsledky výzkumu využívat ve své práci. Nejen proto, aby analýzy nekončily tzv. v šuplíku, ale především aby relevantní lidé byli co nejvíce v obraze a mohli se rozhodovat na základě relevantních informací.

V kontextu vznikajícího analytického útvaru jsme nakonec navrhli řešení ve vymezení části kapacit pro práci na realizaci a zprostředkování výzkumu. Tito lidé mají v popisu práce fungovat jako přemostění mezi analytiky/výzkumníky a věcnými útvary. Mají za úkol propojovat tyto dva světy, ale také rozumět jejich rozdílným potřebám a návykům. Jsou těmi, kdo má rozumět datům spravovaným MŠMT. Mimo jiné se také mají orientovat v procesu zadávání a vedení výzkumu a zdokonalovat jej, aby mohli věcným útvarům efektivně pomáhat realizovat výzkum (ale nedělat výzkum za ně) a měli by mít přehled o všech provedených výzkumech.   

### Vznik analytického útvaru

Šíře našeho zapojení do vzniku analytického útvaru byla poměrně špatně uchopitelná, snažili jsme se naši spolupráci cílit na všechna smysluplná místa v procesu vzniku útvaru.

:::{.aside}
Viz návod [Založení analytického útvaru ->](/pruvodce/vznik-analytickeho-utvaru.qmd)
:::

**Komunikace a konzultace**

Vše již začalo snahou o konzultační podporu při psaní charty projektu a o zapojení ostatních relevantních stakeholderů do procesu psaní charty.  

Průřezově jsme pracovali se zjevným rizikem, že v při přípravě a rozjezdu projektu se nepodaří dostatečně zapojit věcné odbory, které by z něj především měly benefitovat.
Toto riziko jsme identifikovali, protože hierarchická struktukra veřejných institucí spolu s funkční a tematickou specializací jednotlivých útvarů a velkým vytížením viditělně omezovaly prostor pro běžnou horizontální komunikaci mezi útvary. 
Naší snahou proto bylo podporovat triviální princip, který zní asi následovně: 

> Pokud vytváříme nějakou službu pro někoho, musíme se bavit s tím, pro koho tu službu vytváříme, abychom naplnili jejich potřeby.

Proto jsme se snažili co nejvíce incentivizovat setkávání stakeholderů, aby konečné nastavení analytického útvaru co nejvíce naplnilo požadavky všech, ale také aby došlo k mitigaci očekávání. 

**Řízení očekávání**

Je zřejmé, že není možné v podobném projektu naplnit přání a tužby všech, už jen z toho důvodu, že celý analytický útvar je financován z OP JAK a jako takový si musí stanovit konkrétní projektové cíle. 
Snahou tedy nebylo pouze získat vstupy od potenciálních zákazníků útvaru, ale také představit primární náplně práce útvaru. 
Bylo zapotřebí vyjasnit, že analytický útvar není vytvářen pouze pro plnění ad hoc potřeb věcných odborů, ale že primárním zaměřením bude dlouhodobá a koncepční analytika, ovšem navázaná na priority věcných útvarů. 

**Knowledge brokering**

Jak již bylo zmíněno v popisu intervence pro zadávání výzkumu, zamýšleným řešením naplnění potřeb věcných útvarů bylo vytvoření pozic, které mají fungovat jako přemostění mezi analytickým útvarem a věcnými útvary. 
Tato “tykadla” (jak jim sami aktéři začali říkat) mají v popisu práce nejen obstarávat výzkumné a analytické procesy na ministerstvu, ale také komunikovat s věcnými útvary ohledně jejich potřeb a hledání možných řešení (ať již pomocí zadávání nových výzkumů, nebo pomocí odkazování na již proběhlé výzkumy, či datově-analytické činnosti analytické jednotky​).
Jejich role je náročná  především v tom, že jako spojovatelé dvou světů mají mít schopnost vhledu do obou. Mají mít základní přehled o věcné agendě odboru/oddělení, které mají na starost, ale také znát schopnosti a možnosti analytické práce zaměstnanců v daných útvarech. 

Pro zjednodušení jejich práce, která v mnohém spočívá v systematickém uchopování agend a na ně návazných analytických potřeb, jsme společně s kolegy vypracovali tzv. [plachtu agend](/pruvodce/attachments/Plachta agend - web verze.docx).

:::{.aside}
viz návod [Identifikace znalostních potřeb organizace ->](/pruvodce/identifikace-znalostnich-potreb.qmd)
:::

Ta má sloužit jako základní podklad pro spolupráci s věcnými útvary. Snahou bylo nastavit “formálnější” proces, který je lehce předatelný, na který si aktéři mohou lehce zvyknout a který umožní  kvalitnější organizační učení a správy znalostí by tento postup měl napomoci ke dvěma posunům

- Staráme se o “stavy  poznatků” (tj. co už víme, co jsme zjistili dřív), nejen o jejich toky (co se teď potřebujeme dovědět).
- Staráme se o zlepšení poznání k jednotlivým tématům/úkolům ministerstva, ne jen o jednotlivé projekty a výstupy. 

:::{.aside}
viz návod [Péče o analytické výstupy ->](/pruvodce/knowledge-management.qmd)
:::

## Průřezová témata identifikovaná v případové studii

Hlavním postřehem, který je z naší zkušenosti symptomatický pro další aktéry je znatelná nesourodost v řešení jednotlivých agend a starání se o práci s poznatky tak, aby byly využívány podle potřeb. 
Komunikace s ostatními stakeholdery je v tomto smyslu často podceňovaným aspektem. 

:::{.aside}
Více [tezí o práci z poznatky pro týmy](/doporuceni/teze-o-praci-s-poznatky-tymy.qmd)
:::

Dalším je podcenění samotné komunikace výsledků výzkumu. Je zapotřebí mít na vědomí, že samotná kvalita studie nemusí zaručovat její šíření a využití a že komunikace výstupů si zaslouží stejnou pozornost a energii jako její samotné zpracování. To se ovšem v prostorech veřejné správy, kde je časový tlak významný, bohužel ​často děje.  

## Dobré praxe

Samotný vznik analytického útvaru vnímáme jako příklad dobré praxe, jakkoli bude třeba zhodnodit především skutečnou realizaci ve chvíli, kdy útvar vznikne a začne pracovat. Snaha takto významně podpořit práci s poznatky na ministerstvu je velmi pozitivní. Koncepčně-analytické oddělení také z podstaty svých agend nadále vnímá důležitost práce s poznatky a snaží se o její rozvoj a posílení. 

Veškeré společné úsilí, ve kterých jsme společně došli k vytvoření artefaktů, jako je plachta agend či šablona pro zadávání výzkumu, nezůstalo jenom na papíře, ale nový analytický útvar tyto artefakty upravuje podle zkušeností z terénu a aktivně využívá ve své praxi dodnes.  

## Systémové bariéry

- Dostupnost dat ve veřejné správě
- Rozpoznání role analytika ve veřejné správě
- Atraktivnost veřejné správy pro analyticky zaměřené jedince

:::{.aside}
Více k [potřebným systémovým změnám](/doporuceni/systemova-doporuceni.qmd)
:::

## Reflexe spolupráce

Ačkoliv spolupráce začala ve spolupráci se dvěma odbory ministerstva, zaměřili jsme se nakonec především na vznik analytického útvaru a na agendy, které bylo možné nastavit předem a vnímali jsme je jako lehce přenositelné. Jedním z důvodů také bylo, že někteří analytici, kteří přešli do analytického útvaru, pracovali dříve na jednom z těchto odborů. Tudíž spolupráce s nimi dávala největší smysl v kontextu toho, co je čekalo, ne jak věci vypadaly v minulosti. 

Jelikož jsme na začátku projektu o vzniku případného analytického útvaru nevěděli, nebylo možné s takto zásadní změnou počítat a celý proces podle toho nastavit. Podobně jako v jiných zapojených útvarech jsme řešili problémy komunikace, informovanosti, schopnosti definovat problémy a smysluplné využívání poznatků. Myslíme si, že naše společná práce přispěla k citelně lepšímu nastavení analytického útvaru, který má v nadcházejících letech hrát klíčovou roli v práci s poznatky na ministerstvu.    

## Poděkování

Za spolupráci děkujeme především Stanislavu Volčíkovi, Ondřeji Saxovi, Ferdinandu Hrdličkovi, Jiřímu Münichovi, Janu Mušutovi a Jakubu Drbohlavovi, ale také mnohým dalším v celém resortu školství, kteří nám věnovali svůj čas.

Pro další informace můžete kontaktova [Tomáše Čecha](tomas.cech@ceskepriority.cz) v Českých prioritách nebo Stanislava Volčíka (jmeno tečka příjmení zavináč msmt tečka cz) na MŠMT.

