---
title: "MPO: oddělení Smart Specialisation Strategy"
subtitle: "Oddělení S3 kombinuje analytickou, strategickou a koordinační práci v oblasti inovační politiky"
listable: ["listable"]
format: 
  docx: default
  html: default
---

Oddělení S3 na MPO je gestorem [Výzkumné a inovační strategie pro inteligentní specializaci (strategie RIS3)](https://www.ris3.cz/o-ris3/ris3-zakladni-popis-a-smysl). Oddělení S3 vykonává administrativní, analytické a komunikační funkce v souvislosti s implementací strategie RIS3.

# Představení týmu

Strategie RIS3 definuje rámec pro národní a evropské dotační tituly v oblasti podpory výzkumu, vývoje a inovací (dále VaVaI). Oddělení S3 spadá pod Odbor digitální ekonomiky a chytré specializace (Sekce digitalizace a inovací) na MPO.

Agendy oddělení S3 pokrývají administrativní činnosti (komunikace s krajskými úrovněmi, projektová administrace, koordinace národních inovačních platforem, komunikace s Evropskou komisí) a analytické práce (tzv. entrepreneurial discovery process, monitoring a evaluace RIS3 strategie, sběr dat, externí zadávání analytických podkladů pro tvorbu strategie). V oddělení je současně zaměstnáno přibližně 12 lidí.

Analytické aktivity představují pouze zlomek práce v oddělení (cca 20% času), nicméně se jedná o podpůrnou aktivitu pro celou agendu oddělení. Analytické činnosti oddělení spočívají ve sběru a syntéze poznatků pro interní potřeby v rámci koncepční činnosti a designu strategie RIS3, dále pro její samotné  řízení (zejm. monitoring a evaluace). Oddělení S3 ale paralelně generuje výstupy, které využívá řada dalších aktérů v inovačním ekosystému (poskytovatelé evropských a národních podpor, kraje, výzkumné organizace…), zejména metodické podklady k designu procesu objevování podnikatelských příležitostí (EDP), RIS3 misí, dále pak zprávy o realizaci RIS3 strategie nebo podklady pro nastavení podpor a obecněji informace ohledně příležitostí na krajské, národní a EU úrovni.

# Proč se tým zapojil do projektu 

Informované vládnutí (evidence-informed policymaking) je jedním z hlavních stavebních kamenů pro koncepci a implementaci RIS3 strategií napříč EU. [Metodické pokyny](https://s3platform.jrc.ec.europa.eu/guidance), které vydává Evropská komise, doporučují opřít design a implementaci strategie o analytické podklady ohledně současného stavu a potenciálu výzkumného prostředí na národní i regionální úrovni.

Posílení analytických kapacit oddělení S3 tak má přispět ke zkvalitnění těchto podkladů. Vedle toho vykonává oddělení S3 řadu dalších činností, které jsou spíše administrativního a komunikačního rázu, v rámci kterých lze vycházet z vědeckých poznatků pro jejich úspěšný průběh. To se týká například způsobů, jak lépe facilitovat činnost konzultačních platforem (tzv. Národních inovačních platforem prostřednictvím EDP) a zajistit účast širokého spektra relevantních aktérů (tzv. Quadruple helix) v nich. V neposlední řadě se jeví členům týmu klíčový i širší aspekt komunikace s těmito aktéry.

# Diagnostická fáze

Pro získání poznatků do diagnostické fáze byly využity čtyři výzkumné metody: workshopy, polostrukturované rozhovory, pozorování a analýza dokumentů (desk research).

Během úvodního workshopu (30. 11. 2021) se členové týmu představili a popsali své pracovní činnosti. Následně proběhlo 8 polostrukturovaných rozhovorů s členy týmu a vedením. Rozhovory se soustředily na způsoby práce, vnímání překážek pro rozvoj analytických kapacit a úvahy o dílčích intervencích, které by mohly přispět k pozitivním změnám ve fungování týmu. Následně jsme zmapovali vstupní poznatky, výstupy a jejich příjemce a část z nich jsme podrobili podrobnější analýze obsahu i formy.

V závěrečné fázi diagnostické práce jsme realizovali rozhovory s příjemci výstupů. Jednalo se o členy národních inovačních platforem, představitelé krajských RIS3 a řídícího organu OP JAK (MŠMT). Zároveň proběhlo několik pozorování pracovních schůzek (národní inovační platformy, pracovní schůzky ohledně definice RIS3 misí, účast na workshopech ohledně designu misí RIS3).

Během úvodního workshopu byli členové a členky týmu dotázáni ohledně potenciálních směrů rozvoje, které považují za žádoucí v souvislosti s analytickými činnostmi. Mezi hlavními identifikovanými oblastmi bylo řízení týmu s ohledem na interní komunikaci a vzájemnou informovanost a možnosti rozvoje dovedností skrz školení. Další vyjádřené ambice se týkaly způsobů sdílení a dostupnosti dat. V neposlední řadě považovali členové týmu za klíčové umět prezentovat a komunikovat výsledky své práce.

Na základě dalších sesbíraných poznatků ohledně stavu práce s poznatky v době, kdy proběhla diagnostická fáze, shrnujeme níže její hlavní závěry.

## Řízení týmu

Tým byl vnímán jako funkční a profesionální i přesto, že se potýká s nedostatkem personálních kapacit. Aplikace evidence-based přístupů k tvorbě a gesce strategie je explicitně vyžadována a podporována. Vedení se snaží zaujmout aktivní přístup k rozvoji týmu. Tým zaujímá proklientský přístup při komunikaci se zainteresovanými stranami, zejména skrz osobní kontakt.

Potenciálním prostorem pro zlepšení v oblasti řízení týmu byl systematičtější a explicitnější aplikace pracovních postupů pro práci s poznatky. Díky tomu lze zejména zkrátit adaptační proces při náboru nových zaměstnanců.

### Přístup k poznatkům a práce s nimi

RIS3 klade důraz na evidence-based přístupy, což je reflektováno jak v koncepčních činnostech a designu strategie, tak v procesech vedoucích k prioritizaci oblastí podpory VaVaI. Z evaluací a z individuálních rozhovorů vyplynulo, že v posledních letech došlo k značným pokrokům směrem k aplikování evidence-based přístupů.

Z hlediska nastavení procesů lze uvést příklad řízení EDP procesu, který vychází z [analytického podkladu Technologického centra Praha](https://www.mpo.cz/assets/cz/podnikani/ris3-strategie/projekty-na-podporu-ris3/operacni-program-technicka-pomoc/2020/12/Analyza-nastaveni-fungovani-Narodnich-inovacnich-platforem.pdf), ve kterém jsou popsány dobré praxe v zahraničí a v ČR, návrhy systému fungování Národních inovačních platforem a postupy pro jejich efektivní řízení. Z hlediska obsahu se aktualizovaná Národní RIS3 do větší míry opírá o analytické podklady popisující [Klíčové umožňující technologie a jejich vazby na aplikační sféru](https://www.mpo.cz/assets/cz/podnikani/ris3-strategie/projekty-na-podporu-ris3/operacni-program-technicka-pomoc/2020/9/KETs_NRIS_souhrn_zprava_final.pdf). Dále jsou v rámci agendy RIS3 ustanoveny Národní inovační platformy, které mají sloužit pro sběr poznatků z terénu, zejména ohledně definování priorit podpory VaVaI. I přes vysoké nároky na organizaci a koordinaci se daří tyto platformy pravidelně zapojovat do procesů tvorby a implementace strategie. Právě na nutnost informovat a koordinovat různé aktéry navazuje tvorba webové platformy pro usnadnění komunikace (tzv. [RIS3 portál](https://www.ris3.cz/)).

Největší překážkou pro využití analytických kapacit v oddělení S3 byly složité postupy při získávání některých datových sad. Důležitým omezením byla také absence centralizovaného skladiště dat, které by mohli využít členové oddělení pro plnění ad hoc úkolů. Tento nedostatek se však postupně daří eliminovat postupným rozšiřováním datových sad pro oblast VaVaI na RIS3 portálu. Pokud by však byl aplikován ještě systematičtější postup pro aktualizaci a ukládání dat a poznatků (knowledge / data management), může dojít ke značným časovým úsporám.  

## Analytické postupy a metody 

V oddělení RIS3 jsou rozsáhlé analytické práce zadány externě zejména Technologickému centru Praha. Tyto analytické podklady jsou posléze využity v jednotlivých procesních dokumentech, které jsou šířeji sdíleny se zainteresovanými stranami. Monitoring spočívá hlavně v kompletaci datových sad od různých poskytovatelů (Eurostat / ČSÚ, IS VaVaI, MS2021+, data z krajů) a tato činnost se opakuje každý rok. Pro tuto činnost jsou postupy již ustálené a nevyžadují sofistikované metody a nástroje (kontingenční tabulky, grafy).

Hlavní rolí týmu oddělení S3 nespočívá tolik v generování poznatků, ale v jejich syntéze z primárních a sekundárních zdrojů. V této souvislosti ale nejsou ustálené pracovní postupy pro jejich kontinuální monitoring a syntézu. Částečně to může souviset s charakterem a nahodilostí požadavků na takového výstupy. Zároveň sesbírané podněty jsou spíše kumulativní, což je ovšem protichůdné k základním principům RIS3 strategie (prioritizace na místo kumulace).

##  Využitelnost výstupů 

Pro potřeby komunikace celkového rámce strategie RIS3 existují vedle krátkých metodik stručné informační podklady ve formě powerpointových prezentací. Tento formát je adekvátní vzhledem k cílovým skupinám, které nemají vždy kapacitu přečíst celý psaný dokument. Členové týmu v oddělení S3 si jsou zároveň vědomi, že je nutné přizpůsobovat komunikaci různým zainteresovaným skupinám a uvažují o dalších možných formách komunikace, které by mohly doplnit formální textové dokumenty (např. branding, PR a marketing, vizualizace).

Některé výstupy (např. Národní RIS3 strategie a její přílohy) jsou velmi obsáhlé (přes 300 stran) a chybí stručná syntéza klíčových informací, která by byla využita při komunikaci s externími partnery.

Prezentace dat a indikátorů pro monitoring RIS3 původně neodpovídala standardům open data (complete, primary, timely, accessible, machine processable, non-discriminatory, non-proprietary, license-free). Indikátory byly dostupné pouze z tabulky ve formátu PDF, což zásadně limitovalo možnosti jejich dalšího využití. Nedávno spuštěný RIS3 portál situaci o něco zlepšil (publikace datových tabulek /dashboardů), zároveň s sebou nese potřebu vhodně využít nové technické možnosti pro efektivní komunikace dat vzhledem k různým adresátům sdělení.

# Intervence

Na základě výše uvedených poznatků o současném stavu analytické práce na oddělení S3 jsme týmu S3 navrhli několik oblastí pro rozvoj intervencí. První tři se týkají věcné / obsahové práce v souvislosti s designem a implementací RIS3. Konkrétně jde o design nových prvků do strategie (např. mise) a zajištění široké participace v EDP procesu ("quadruple helix").

Navrhli jsme také podpůrné intervence, které cílí na zkvalitnění analytických aktivit v oddělení S3. Tyto intervence měly obecnější charakter, ale ze své podstaty měly pomoci k naplnění výše uvedených cílů. Zaměřily se na následující oblasti: tvorba plánu analytických činností, knowledge management týkající se pracovních postupů, prezentace a zpřístupňování dat, externí komunikace a marketing strategie RIS3.

Vzhledem k časové vytíženosti členů oddělení S3 jsme se rozhodli prioritizovat intervence podle současných potřeb a možností týmu.

## Uživatelské testování webového produktu

První intervence navazovala na spuštění webového RIS3 portálu (podzim 2022) a na mid-term evaluaci, která mimo jiné zkoumala funkčnost tohoto webového portálu. Proto jsme společně s administrátorem webového portálu navrhli postup pro jeho uživatelské testování s vybranými uživateli. Další dílčí intervence související s webovým portálem měla za cíl poskytnout technickou podporu pro datově vizualizační modul.

Tým S3 vytvořil (formou veřejné zakázky) a udržuje webovou aplikaci RIS3 portál. V zájmu posílení jejich využitelnosti a přehlednosti jsme navrhli postup, jak testovat webový produkt přímo s uživateli pomocí metod uživatelského designu (UX design).

Výsledkem je návod [Uživatelský výzkum a testování webového produktu →](/pruvodce/user-testing.qmd)

## Realizace syntetických analytických zpráv

Druhá intervence měla za cíl navrhnout postup pro realizaci syntetické analytické zprávy pro podporu designu nových koncepčních prvků v RIS3. Konkrétně se jednalo o zapojení veřejnosti do EDP procesu, kde bylo zapotřebí zmapovat překážky pro jejich zapojení a navrhnout způsoby jejich řešení.

Analytické výstupy, které generují členové týmu S3, jsou využívány interně i externě, a proto je vhodné v přípravných fázích pochopit potřeby těchto uživatelů a přizpůsobit jim obsah i formu analytického výstupu. Paralelně jsme se pokusili o aplikaci inovativních nástrojů pro rešerši literatury, zejména pomocí umělé inteligence.

Zkušenosti z této části spolupráce jsme promítli do návodu [Kvalitní a efektivní zprávy →](TODO LINK)

# Dobré praxe v týmu

Tým zaujímá proklientský přístup při komunikaci se zainteresovanými stranami, zejména skrz osobní kontakt. Pro potřeby komunikace celkového rámce strategie RIS3 existují stručné informační podklady, které jsou adekvátní vzhledem k cílovým skupinám, které nemají vždy kapacitu přečíst celý psaný dokument.

I přes vysoké nároky na organizaci a koordinaci se daří EDP platformy pravidelně zapojovat do procesů tvorby a implementace strategie. RIS3 strategie je tedy příkladem strategického dokumentu, který je živý i prostřednictvím průběžného zapojení stakeholderů do jeho řízení.

Tým S3 využívá evropských sítí a expertizy (zejm. Společné výzkumné středisko Evropské komise - JRC) pro odbornou podporu svých agend. Nedávno tato spolupráce vyústila v [doporučení](https://www.ris3.cz/aktuality/novy-pohled-na-inovacni-politiku-prinasi-studie-mpo-a-jrc) pro design a implementaci nového nástroje podpory výzkumu a vývoje - RIS3 mise.

Oddělení S3 zároveň buduje tuzemskou síť specializované expertizy pomocí projektu [„Strategická inteligence pro výzkum a inovace“ (STRATIN+)](https://stratin.tc.cas.cz/), na kterém se podílí Technologické centrum Praha, Sociologický ústav AV ČR, EURAXESS a Národní vzdělávací fond. MPO také navázal spolupráce v tématu inovací napříč veřejnými organizacemi (zejm. Czechinvest a TA ČR). 

# Zobecnitelnější vhledy

TODO prolinky na teze a systémová doporučení

V oddělení S3 se koncentrují všechny činnosti spojené se strategickou prací, od koncepce po koordinaci, ale také poskytování dat a podkladů do celého výzkumného a inovačního prostředí a síťování všech aktérů. Ukazuje to na realitu práce s poznatky, která je často **součástí širší agendy** (např. řízení strategií) zahrnující jak operativu či implementaci, tak strategickou práci. Kvalita práce s poznakty má podstatný vliv na celkový výsledek, ale útvar -- a často ani jednotlivci -- kteří tuto práci vykonávají by se sami za analytiky neoznačili.

Přestože se nejedná o čistě analytický útvar, oddělení S3 má vybudovanou odbornou kapacitu v tématu podpory výzkumu a vývoje a **vytváří datové produkty** (především RIS3 portál) pro celý ekosystém. 

**Know-how pro práci s daty je koncentrovaná v jednom až dvou** členech týmu, což je relativně běžné i v jiných analytických útvarech (např. na ASZ). To přináší výhodu z hlediska budování know-how, nicméně se tím zvyšuje i závislost na těchto členech týmu a případné riziko při výpadku či odchodu člena týmu. Specificky v oblasti dat vzniká také riziko, že postupy pro správu dat (data management) nejsou zexplicitněny a aplikovány napříč týmem.  

Během projektu se ukázalo, jak užitečné může být vyhledat expertizu i mimo veřejnou správu, zejména pro aplikaci technických postupů. V našem případě se přes odborné komunity (Datavis Meetup Brno) podařilo najít člověka z technologické firmy, který pracoval s vizualizačním nástrojem, který je v Česku relativně méně využívaný, je ale integrován do systému RIS3 portálu. Díky tomu členové týmu získali rady a pomoc při řešení problémů od experta z jiného sektoru.

# Systémové bariéry

TODO prolinky na systémová doporučení

Oblast veřejné podpory výzkumu a vývoje se v Česku vyznačuje velkým počtem aktérů a roztříštěností zodpovědností. V kontextu strategie RIS3 je tato fragmentace ještě posílená tím, že tvorba a řízení strategie je organizačně oddělená od rozhodování ohledně finanční podpory v rámci evropských i národních dotačních titulů, a to i v rámci ministerstva.

Aktivity na podporu implementace strategie (vč. analytické práce) jsou z podstatné části hrazené skrz evropské fondy formou projektového financování. V důsledku jsou tyto aktivity rozvíjeny v krátkých časových rámcích typických pro projektové financování (2-3 roky), což ohrožuje jejich kontinuitu a zvyšuje nejistotu členů týmu ohledně jejich budoucího působení. 

# Kontakt a poděkování

Pokud Vás příběh týmu zajímá, kontaktujte vedoucího oddělení S3 na MPO [Tomáše Holinku](mailto:holinka@mpo.cz) nebo Alexe Reznikowa v Českých prioritách. 

*Děkujeme také dalším kolegům z oddělení S3 na MPO: Janovi Bilíkovi, Janě Fišerové, Ivaně Križanové, Michaele Novotné, Lence Paříkové, Jiřímu Turkovi a Dagmar Vránové.*
