---
title: "Doporučení pro stát"
editor: source
title-block-banner: true
toc-title: "Oblasti doporučení"
format:
  html:
    toc-depth: 1
  docx: default
aliases: 
  - /doporuceni-system
  - /systemova-doporuceni
  - /doporuceni/system
---

> Při práci na rozvoji práce s poznatky se zapojenými týmy jsme opakovaně naráželi na **bariéry způsobené nějakým systémovým nedostatkem** -- nastavením pravidel, absencí podpory, apod.
>
> Níže tyto bariéry zachycujeme jako **oblasti, kde je potřeba nějaká změna na úrovni systému**. Někdy to znamená změnu legislativy či jiných pravidel, někdy změnu ve způsobu práce průřezových agend, např. personalistiky.
>
> **Adresátem** těchto doporučení jsou především ti, kteří mohou těmto změnám pomoct: vesměs gestoři tématu rozvoje veřejné správy, vedení státní služby, ale také vyšší management a státní tajemníci ministerstev.
> 
> Doporučení často **navazují a odkazují** na již zvažované nebo plánované iniciativy a ukazují na jejich potřebnost nebo zpřesňují cíl. Měla by proto být realizovatelná v současném kontextu české veřejné správy. Pokud navrhujeme inovativnější opatření, jsou inspirována funkční praxí z jiných států.
> 
> Doplňkem k doporučením jsou naše vzkazy o práci poznatky [pro stát](/doporuceni/teze-o-praci-s-poznatky-stat.qmd) a pro [samotné týmy ve státní správě a jejich členy](/doporuceni/teze-o-praci-s-poznatky-stat.qmd). Ty je vhodné číst pro lepší porozumění předpokladům a poznatkům, ze kterých při formulaci doporučení vycházíme.

# Struktury a procesy podporující využívání poznatků {#struktury}

## Stabilnější analytické kapacity {#stabilnejsi}

**Co je problém**: analytickým kapacitám chybí finanční a organizační stabilita

**Co doporučujeme**

- Vedení státní služby a MV jako gestor tématu analytické práce by mělo udržovat přehled o analytických kapacitách napříč státní správou, včetně způsobu jejich financování
- identifikovat klíčové kapacity, které by měly z projektového financování přejít do jádrové kapacity státu financované ze státního rozpočtu

**Co by tomu ještě pomohlo**

- Definovat pozici analytika, ještě lépe šířeji definovanou profesi navázanou na kariérní postup (tzv. profesní kariérní linka) 
- Pracovní (versus služební) místa ve státní službě využívat spíše obezřetně
- Jako opatření pro snížení dopadů personální nestability lze posílit správu znalostí (např. repozitáře výstupů) a kanály sdílení mezi experty; tyto spíše technické nástroje ale nevyřeší podstatu problému
- Podobně lze podpořit mobilitu jednotlivců mezi resorty, popř. meziinstitucionálních popř. meziresortních týmů; tím by se opět snížil dopad nestability jednotlivců na daných pracovních místech za předpokladu, že daní lidé alespoň zůstanou uvnitř systému

**Proč je to třeba** 

Uvnitř státní správy je velká část analytiků a analytiček zaměstnaná na projektech financovaných EU fondy, které ale ze své podstaty nepředstavují stálá pracoviště, na nichž by bylo možné budovat analytické kapacity. Logika projektového řízení vede k přetrhávání kontinuity, nedostatku času k vybudování institucionalizovaného know-how, a prioritizaci generování výstupů místo zázemí a infrastruktury.

Dále existuje riziko vzniku nerovností v analytických možnostech uvnitř státní správy, jelikož projekty EU fondů mají vzhledem k finančním prostředkům větší možnosti zaměstnávat zručné analytiky a analytičky (alespoň​ zatím). Delegování analytické práce na pracoviště (dočasně) financované ESIF ale zároveň signalizuje, že budování analytického týmu a know-how není pro stát prioritou. 

## Lepší propojení věcných a implementačních útvarů {#propojeni}

**Co je problém**: věcné a implementační útvary jsou často příliš oddělené, což brzdí i analytickou práci a využívání poznatků.

**Co doporučujeme**

Státní tajemníci a vrchní ředitelé sekcí by měli 

- při úvahách o organizačních změnách pečlivě zvažovat, jak organizačně nastavit vztahy mezi věcnými, analytickými a implementačními útvary v příbuzných tématech. 
- pracovat s organizační strukturou -- popřípadě jinými nástroji tak, aby napomáhaly toku informací a efektivní spolupráci mezi věcnými gestory, tvůrci veřejněpolitických nástrojů (např. dotačních titulů) a analytickými kapacitami.

**Proč je to třeba** 

Lepšímu využívání poznatků v tvorbě politik brání to, že na řadě ministerstev jsou věcné útvary oddělené od implementačních -- často se nacházejí v jiných odborech či dokonce sekcích. Věcná oddělení pak nejsou schopna efektivně dodávat svým implementačním protějškům zadání; obecně komunikace mezi nimi vázne.

To pak také vede k fragmentaci a duplikaci analytických kapacit, které se budují ad hoc na implementačních odděleních. Jednou z příčin tohoto problému je budování specifických kapacit ze zdrojů EU fondů, které jsou ale často v systému ministerstev postaveny mimo stálé útvary zabývající se těmi stejnými tématy.

## Snadnější vznik projektových týmů {#projektove-tymy}

**Co je problém**: funkční specializace a personalistická pravidla znesnadňují vznik projektových týmů, což zhoršuje podmínky pro informované rozhodování.

**Co doporučujeme** 

Státní tajemníci a vrchní ředitelé by měli:

- při rozhodování o organizační struktuře zvážit možnost vytvářet multifunkční, multioborové týmy
- podporovat projektové řízení pro koordinaci projektových týmů napříč útvary

Vedení státní služby, popř. zákonodárce:

- umožnit v legislativě mobilitu zaměstnanců napříč státní správou
- umožnit větší flexibilita systemizace 
- podporovat projektové řízení pro koordinaci projektových týmů napříč útvary

**Proč je to třeba** 

Současná struktura státní správy je organizována podle funkcí a profesí a zaměření jednotlivých oddělení, které se specializují na danou agendu, popř. specifickou činnostu v rámci agendy. Toto nastavení zabraňuje flexibilnějšímu vznikání týmů na projektové bázi, které by se po určitou dobu věnovaly konkrétními problému, což může být vhodnější model pro potýkání se se společenskými výzvami a využívání poznatků pro jejich řešení.

# Uznané a podporované role {#role}

## Profese analytika {#profese}

**Co je problém**: Na rozdíl od některých jiných profesí není role analytika ve státní službě definovaná a uznaná.

**Co doporučujeme** 

Není v našich silách navrhnout kompletní řešení ukotvení role analytika ve státní službě, ale nabízíme několik kontur, které by takové ukotvení mělo mít:

- Typové role: zřejmě nepůjde o jednu standardizovanou profesi či roli, ale o širší profesi s několika specializacemi -- např. britský stát v tomto směru staví [kariérní rámec analytiků](https://analysisfunction.civilservice.gov.uk/careers/career-framework/).
- Je možné vycházet také ze standardu, jak se taková profese vykonává; tento přístup volí např. britská státní správa [@hmgovernmentGovernmentFunctionalStandard2023]
- Součástí profese by měla být předvídatelná kariérní dráha, tj. např. postup po kariérní lince (což je širší problém řízení státní služby)
- Pro rozvoj profese je vhodné mít viditelné lídry např. na jednotlivých ministerstvech nebo napříč službou

Z těchto náčrtů je patrné, že si nejsme jisti, zda by profesionalizaci role analytika prospělo zařazení mezi obory služby s příslušnou zkouškou ve stávajícím systému zákona o státní službě.

**Proč je to třeba** 

Obecným systémovým problémem práce s poznatky je absence uchopení analytika/čky jako specifické profese. Problematické v tomto ohledu není to, že není zavedena přesná definice, což by naopak vzhledem k šíři práce s poznatky ve veřejném sektoru mohlo být zbytečně omezující. Deficitem současného neuchopení analytické profese je to, že následně neexistuje etablovaná komunita, v níž by mohlo docházet k výměně zkušeností a vzájemnému se učení, odborný rozvoj, profesní identita a související motivace se rozvíjet. (Jakkoli je přínosné PSSAÚ jako platforma vzniklá odspoda.) Dále pak chybí více institucionalizované mechanismy jako společný onboarding nebo přehled základních datových a informačních zdrojů.  

## Personalistické procesy jako podpora práce s poznatky {#personalistika}

**Co je problém**: Běžná personalistická praxe -- např. nábor, proces adaptace a kroky při odchodu pracovníků -- neslouží jako podpora pro udržování a předávání poznatků.

**Co doporučujeme** 

Ani zde nejsme vzhledem k naší expertize a zkušenostem z praxe schopni navrhnout řešení, ale je patrné, že např. správě a uchovávání poznatků by pomohly jakékoli kroky, které by podpořily týmy a manažery v zavedení a využívání standardních procesů předávání a uchovávání poznatků v klíčových momentech "životního cyklu" zaměstnance: při nástupu, při změně pozice, při odchodu. 

**Proč je to třeba** 

Toto slabé místo se pravděpodobně projevuje nejen u týmů a jednotlivců intenzivněji pracujících s poznakty, zde jsme ale v naší zkušenosti se zapojenými týmy tento deficit pozorovali silně. Práce s poznatky je velmi závislá na získaných znalostech, dovednostech a kontaktech, které často nejsou nikde kodifikované a proto jsou náchylné ke ztrátě v momentech personální diskontinuity.

## Policy analysis jako klíčová aktivita státu {#policy-analysis}

**Co je problém**: tvorba a analýza politik není viděna jako klíčová aktivita veřejných institucí

**Co doporučujeme**: 

Procesu tvorby politik by prospělo, kdyby analýza a tvorba politik byly považovány za základní proces státní správy a podle toho státní služba uvažovala o potřebných kapacitách, dovednostech a organizačních faktorech. Bez dalšího zkoumání není zjevné, jaké kroky k tomuto stavu mohou vést; mohlo by se jednat např. o redefinici oborů služby a proměnu vstupního, resp. průběžného vzdělávání. Vítaným impulsem tímto směrem může být i posílení role metodik RIA v procesu přípravy legislativy.

**Proč je to třeba**: 

V současnosti jsou činnosti spojené s tvorbou politik a opatření často uvažovány odděleně: analýza dat, tvorba legislativy, evaluace, aj. Dílčí výjimkou je strategické řízení, které má svou metodiku a odbornou komunitu; velká část státních zaměstnanců, kteří tvoří veřejné politiky a veřejněpolitické nástroje, se ale nepovažuje za stratégy a sféru strategií tedy nepovažuje za svou. 

Takovéto uchopení aktivit, které jdou často napříč útvary a obory, by také usnadnilo propojování mezi světem analytiků a světem věcných expertů či tvůrců legislativy.

V tomto se česká státní správa liší od mnohých rozvinutých států, které "policy making" považují za ucelenou roli a profesi uvnitř státní služby.

# Lepší schopnosti a dovednosti {#schopnosti}

## Základní schopnosti práce s daty jako standard {#schopnosti-standard}

**Co je problém**: Chybí postupy, jak dosáhnout základních schopností práce s poznatky a daty u širokého spektra úředníků 

**Co doporučujeme** 

- začlenit základní znalosti a dovednosti práce s daty a poznatky do standardního rozvojového kurikula větší části úředníků (státních zaměstnanců)
- zvážit zahrnutí těchto témat (především základního přehledu např. o zdrojích dat a metodách práce s nimi) do základní části úřednické zkoušky
- tímto směrem upravit i okruhy zvláštní části u relevantních oborů úřednické zkoušky

**Co by také pomohlo**

- upravit systém hodnocení tak, aby motivoval k rozšiřování znalostí a dovedností i v oblasti práce s poznatky

**Proč je to třeba**

V současném fungování veřejné správy neexistují mechanismy, které by pomohly zajistit základní schopnosti práce s poznatky a daty u širšího spektra úředníků a úřednic, například ve formě úvodního “evidence bootcampu”.

Z naší zkušenosti s relativně rozličnými týmy víme, že základní přehled, znalosti a dovednosti potřebují i ti státní zaměstnanci, pro které není analytická práce hlavní součástí jejich činnosti.

Toto se netýká pouze “tvrdé” datové práce, ale i obecnější schopnosti výzkumné činnosti včetně zadávání výzkumu analytickým oddělením. Tato absence podpory a motivací rozvoje datových a souvisejících schopností je přítomná i v náboru, kontinuálním vzdělávání a hodnocení. 

## Vzdělávání v práci s poznatky {#schopnosti-vzdelavani}

**Co je problém**: V současné době neexistují komplexní vzdělávací schémata, která by zaměstnance a zaměstnankyně státní správy připravila na práci s poznatky. 

**Co doporučujeme** 

Zde nenabízíme konkrétní řešení (tj. jaké typy rozvojových intervencí zvolit a jak by měly vypadat), ale naznačujeme několik principů, kterými by se proces vývoje takového kurikula měl řídit:

- sestavit tým lidí, který návrh kurikula vytvoří -- využít etablované experty zevnitř státní správy, např. ty s označením vynikajících všeobecně uznávaných odborníků 
- do designu kurikula zahrnout externí expertizu (akademici, pracovníci think tanků a dalších organizací, které se státní správou pracují např. jako dodavatelé poznatků)
- ve vzdělávacích intervencích využít existující interní expertizu napříč resorty a organizacemi
- reflektovat zkušenosti a zpětnou vazbu z pilotního programu pro analytiky veřejné správy
- prioritizovat rychlý vývoj a testování kurikula před dokonalým řešením vytvořeným za dlouhou dobu
- u problému rozvoje vedoucích analytických týmů pracovat s rozvojem na základě sdílení zkušeností a skupinové reflexe např. vedoucích nově vznikajících analytických útvarů

Jak vysvětlujeme ve [vzkazech pro stát](teze-o-praci-s-poznatky-stat.qmd), rozvoj analytiků by měl z významné části stát na učení se od druhých a využívání a sdílení existující expertizy a dovedností. Stejně tak by součástí rozvojových intervencí mohly být interní stáže, které využívají mnohé státní služby v zahraničí a jako smysluplné je hodnotili i členové týmu v [jedné z našich případových studií](/pripadove-studie/case-tacr.qmd).

Pro definování relevantních znalostí a dovedností, které by program měl budovat, lze využít např. rámec vyvinutý Joint Research Center [@schwendingerCompetencesPolicymakingCompetence2022] a pro zacílení na různé role a typy analytiků lze využít [@olejniczakRoleAnalystsPublic2018 resp. @howlettPolicyAnalyticalCapacity2015 viz obr. 1 na s. 175].

Jako inspirace může sloužit i funkční standard [@hmgovernmentGovernmentFunctionalStandard2023] a [kompetenční model](https://analysisfunction.civilservice.gov.uk/careers/role-profiles-and-career-pathways/) britské státní služby pro analytickou profesi.

**Proč je to třeba**

V některých oblastech veřejné správy existují sady vzdělávacích kurzů a programů zaměřených na ucelený rozvoj specialistů na danou oblast - příkladem jsou personalistika, veřejné zakázky či EU fondy. V oblasti práce s poznatky tomu tak není -- zřejmě i proto, že se nejedná o konkrétní agendu, ale sadu průřezově využitelných dovedností. 

Z dílčí zpětné vazby státních zaměstnanců vyplývá, že v některých tématech v této oblasti chybí na trhu vhodné kurzy a některé vzdělávací intervence by bylo vhodné vyvinout specificky pro potřeby veřejné správy, aby prostředky na vzdělávání přinesly skutečně aplikovatelné učení. 

Narozdíl od zmiňovaných oblastí v tématu práce s poznatky (analytické práce) platí, že by takový program měl být modulárnější a umožňovat výběr témat a dílčí specializaci jednotlivců; nelze předpokládat, že by každý měl absolvovat celé stejné kurikulum. (Zde viz [typové role, které identifikuje britská státní služba](https://analysisfunction.civilservice.gov.uk/careers/role-profiles-and-career-pathways/)).

Specifickým problémem pak jsou dovednosti pro vedení analytických týmů. Ani zde neexistuje profesní příprava.

## Nejen pro experty a řadové analytiky {#schopnosti-manazeri}

**Co je problém**: Základní povědomí o práci s poznatky někdy chybí i na úrovni vedoucích pracovníků (představených).

**Co doporučujeme** 

V této oblasti nedáváme doporučení, protože to přesahuje naše poznání tohoto problému a jeho možných řešení.

**Proč je to třeba**

Představení nemají být experty na analytickou práci, ale nějaká míra znalostí a dovedností je zásadní pro jakýkoli posun kultury a praxe veřejné správy směrem k informovanému vládnutí (evidence-informed decision making). Z našeho pozorování týmů v oblasti práce s poznatky jsme identifikovali, že zásadní jsou především schopnosti manažerů v následujících oblastech:

- identifikovat znalostní potřeby pro práci útvarů a veřejněpolitická rozhodnutí
- klást empirické otázky a formulovat zadání analytických úkolů a projektů - tedy být efektivním zákazníkem pro analytickou práci
- vyhodnotit relevanci a kvalitu poznatků, které k nim přicházejí
- přehled o standardech a možnostech současných postupů a metod v oblasti tvorby a vyhodnocování veřejných politik

Nedostatky v této oblasti vedou kromě nekvalitního rozhodování také k neefektivnímu využívání existujících analytických kapacit, případně k demotivaci analytiků.

## Nábor a platy umožňující přitáhnout talent {#nabor}

**Co je problém:** Úroveň a struktura platů znesnadňuje přitahování talentovaných kandidátů na analytické pozice.

**Co doporučujeme** 

V této oblasti nemůžeme dát konkrétní doporučení, protože oblast odměňování je komplikovaná a citlivá, navíc dílčí změny jsou v jednání.

Že kromě větší úpravy platových úrovní, struktury platových stupňů a tabulek a větší flexibility v odměňování (včetně hojnějšího využívání stávajících možností) by pomohla i větší platová transparentnost a aktivnější přístup k náboru.

Protože některé nástroje platové flexibility jsou navázány na obory služby, neexistence oborů služby zachycujících analytické činnosti zde omezuje schopnosti zaměstnavatelů využít flexibility pro zatraktivnění pozic.

**Proč je to třeba**

Analytické dovednosti -- včetně technických, např. práce s daty -- jsou silně poptávané v soukromé sféře, horší platová nabídka státu se tedy v této oblasti projevuje obzvláště silně.

# Dostupnější zdroje dat a informací {#zdroje}

## Snadnější přístup k datům veřejného sektoru {#zdroje-data}

**Co je problém:** Mnohá data veřejného sektoru, zejména administrativní a statistická mikrodata, nejsou dostupná pro analytické účely.

**Co doporučujeme** 

Prosadit zákon o správě dat veřejného sektoru v takové formě, která umožní přístup k mikrodatům pro analytické účely.

**Proč je to třeba**

Kromě samotné možnosti analytiků využívat data je jejich zpřístupnění pro vědecké a výzkumné účely potřebné i proto, aby se posílila schopnost akademické sféry produkovat výzkum využitelný veřejnou správou.

Jak pro výzkum, tak pro analýzy ve veřejném sektoru platí, že využití ve světě běžných metod např. hodnocení dopadů, stejně jako cílení politik a dobrá definice řešených problémů, se neobejdou bez přístupu k administrativním mikrodatům, tj. typicky datům na individuální úrovni.

Zkušenosti mnohých států ukazují, že je možno toho dosáhnout zároveň se zachováním potřebné úrovně ochrany údajů.

## Dostupné akademické zdroje {#zdroje-akademicke}

**Co je problém:** Velká část akademických výzkumů není pro zaměstnance státní správy dostupná.

**Co doporučujeme** 

Jako řešení se nabízí, aby např. státní správa jako celek pořídila přístupy do zásadních akademických databází. V této oblasti nemáme dostatečné informace, abychom dokázali vyhodnotit, jaké řešení by bylo prakticky a finančně schůdné.

Součástí řešení pravděpodobně je i posílení motivace vědců k publikování formou open access, což ale spadá do domény podpory výzkumu a vývoje.

## Snadněji nalezitelné výstupy veřejného sektoru {#zdroje-vystupy}

**Co je problém:** Neexistuje způsob, jak spolehlivě vyhledat zveřejněné výstupy analytické práce veřejných institucí.

**Co doporučujeme** 

Vytvořit a zpřístupnit repozitář studií.

Systém by měl být pokud možno co nejjednodušší.

Lze se inspirovat např. [knihovnou evaluací EU fondů](http://dotaceeu.cz/knihovna-evaluaci), včetně některých zkušeností ohledně vhodné míry komplexity systému a jeho uživatelské přívětivosti.

**Proč je to třeba**

Nejedná se pouze o opatření směrem k transparentnosti vůči veřejnosti; veřejný nebo částečně veřejný repozitář studií je nejsnadnějším způsobem, jak zpřístupnit výstupy i napříč státní správou.

# Podmínky pro zlepšování práce s poznatky {#podminky}

## Leadership a klíčové role  {#podminky-role}

**Co je problém:** V několika oblastech zásadních pro práci s poznatky neexistují viditelní lídři tématu.

**Co doporučujeme** 

Jedním z možných řešení by bylo ustanovit existující seniorní manažery či expertů do rolí jmenovaných odborných lídrů pro specifické oblasti, např.:

- správa dat -- potenciálně i Chief Data Officer úřadu
- analýza dat a výzkum (viz role tzv. Chief Analysts v některých zahraničních státních správách)
- vědecké poradenství (viz role tzv. Chief Science Advisors ministerstev v některých státech)
- správa znalostí

Tyto designace by mohly existovat v některých nebo všech ministerstech nebo napříč centrální státní správou. V některých variantách by bylo možné tyto role navázat na kariérní linku rozvoje nebo existující institut vyníkajících, všeobecně uznávaných odborníků.

Lze navrhnout různé varianty těchto rolí, lišící se např. tím, jaký má vztah k definování standardů, vzdělávacích programů či přímo k zodpovědnosti za kvalitu práce v dané oblasti v dané instituci ci napříč institucemí, popř. může jít naopak o role více neformální.

**Proč je to třeba**

Rozvoj dovedností a kvality práce v těchto oblastech nemůže být jen věcí standardů, postupů a školení, ale je třeba mít také viditelné zastánce rozvoje a profesní vzory.

## Standardy a podmínky pro práci s daty {#podminky-datarina}

**Co je problém**: v oblasti analýzy dat se zásadně liší přístupy, technologie a postupy běžně používané ve státní správě od těch běžných v soukromém sektoru.

V posledních letech se velká část soukromého sektoru v oblasti analýzy dat posouvá k využivání open source nástrojů analýzy dat (Python, R, Julia aj.), v datové analytici se využívají nástroje a postupy známé ze softwarového vývoje (git, nástroje kontinuální integrace a vývoje - CI/CD) a větší systémy se staví modulárně z volně dostupných open source komponent (tzv. Modern Data Stack). Tyto přístupy a nástroje nejsou ve veřejné správě běžné, byť se také rozšiřují a část z nich používají mnozí individuální analytici a týmy, často ale systému poněkud navzdory.

**Co doporučujeme**

- stanovit standard softwarových nástrojů, které by měly být dostupné, popř. rovnou nabízené, ve všech organizacích
- poskytnout centrální stanovisko ohledně využívání open source nástrojů pro analýzu dat
- identifikovat, které z nástrojů už jsou dostupné např. pro účely in-house vývoje softwarových aplikací a umožnit jejich zpřístupnění datovým analytikům
- ke zvážení je sdílený cloud prostor pro práci s daty (některé organizace např. už dnes využívají prostředí Azure ML Studio)
- identifikovat jednotlivce a týmy, kteří už využívají současné technologie a postupy a umožnit jim šířit své know-how
- podpořit provoz a využití systému [code.gov.cz](https://code.gov.cz)

**Další možnosti ke zvážení**

- podpořit rozvoj komponent (knihoven, šablon) využitelných napříč státní správou v často využívaných nástrojích (Python, R) - podobně jako pro vývoj webů Design System gov.cz
- podpořit vznik skupiny analytiků, kteří tyto nástroje již používají, popř. rozšířit na systém ambasadorů na resortech
- podpořit vývoj standardů práce a souvisejících nástrojů - zde inspirací může být iniciativa analytické profese britské státní služby [Reproducible Analytical Pipelines](https://analysisfunction.civilservice.gov.uk/policy-store/reproducible-analytical-pipelines-strategy/), což je sada opakovaně využitelných nástrojů usnadňujících automatizaci analytických postupů a procesů.
- podpořit využívání moderních přístupů metodikami (např. v oblasti RIA, popř. v potenciálním peer review mechanismu podle slovenského modelu), kde součástí kontroly kvality (např. u RIA hodnotící zprávy) bude ověření splnění základních standardů kvality práce s daty. Zde mohou být inspirací metodiky britské státní služby tzv. Duck Book [@ukgovernmentanalyticalcommunityQualityAssuranceCode2022] a Aqua Book [@hmtreasuryAquaBookGuidance2015] a částečně i Magenta Book [@hmtreasuryMagentaBookCentral2020].
- prověřit možnost využít DIA resp. center kompetence pro tuto oblast
- ucelenou sadu doporučení pro organizace v podobné situace nabízí britské tzv. Goldacre Review: studie, která navrhuje výrazné posílení datově analytických kapacit a zakotvení moderních postupů v této oblasti v zdravotnickém systému [@goldacreBetterBroaderSafer2022].

**Proč je to třeba**

Příčinou je zřejmě jak běžná úroveň a zaměření technických dovedností datových analytiků (dominantně Excel), tak dostupnost a podpora relevantního softwarového vybavení. Např. na ministerstvech není běžné mít k dispozici sdílené prostředí pro práci s kódem otevřené pro analytiky, stejně tak může být v některých organizacích problém dosáhnout zpřístupnění open source nástrojů, ke kterým úřad z definice nevlastní licence a může mít obavu z bezpečnostních rizik.

Současný stav vytváří personální a technologické bariéry mezi soukromým a veřejným sektorem. Brání mobilitě expertů -- ti ze soukromého sektoru se zájmem o přechod do veřejného nemohou počítat s>prine tím, že budou moci využívat pro ně běžné postupy a nástroje; ti uvažující např. o startu kariéry ve veřejném sektoru nemohou počítat s tím, že se naučí nástrojům běžným jinde. 

Především ale existující stav omezuje škálu nástrojů a metod, které stát běžné využívá a potenciálně vede k nákupu komerčních řešení či přímo řešení na zakázku tam, kde by open source nástroje přinesly stejný užitek s nižšími náklady.

## Audit a kontrola motivující k práci s poznatky {#podminky-audit}

**Co je problém**: auditní a kontrolní aktéři mohou nezamýšleně omezovat motivaci k empirické práci popř. inovacím šířeji

**Doporučení pro auditory a kontrolory**

- při formulaci závěrů zvažovat, zda nemohou přinést nežádoucí efekt oslabení využívání poznatků
- reflektovat nutnou nejistotu a riziko v oblasti analýzy politik, evaluace apod. - často jde o de facto inovační aktivity a přílišný důraz na dosažení předem definovaných výstupů může potřebnou inovaci dusit
- při hodnocení práce veřejných institucí brát v potaz i to, zda se daná instituce snaží o využívání poznatků pro design opatření a jejich vyhodnocování; za ex post hodnocení, kde úřad sám identifikuje např. nedokonale fungující intervenci, by měl úřad být pochválen, nikoli kritizován.

**Proč je to třeba**

Logika auditu a indikátorů, které v současnosti slouží ke kontrole a auditu státní správy ve vztahu ke kritériím hospodárnosti resp. 3E, může nezáměrně vést ke snižování motivace k analytické práci a přijímání inovativních postupů obecněji. 

Setkali jsme se s několika situacemi, kdy zaměstnanci státní správy při úvaze o zadání analýzy nebo využití nějaké metody zvažovali, zda mohou na sebe vzít riziko např. že se nepodaří danou metodu zrealizovat (např. kvůli problému s daty), což by mohly auditní a kontrolní postupy zhodnotit jako neúčelné využití prostředků. Podobně jsme se setkali se situacemi, kdy se zaměstnanci obávali některé informace zjišťovat. I když je by zajímaly a dokázali by je využít např. pro zlepšení nějakého opatření, obávali se, že tuto informaci by mohl kontrolní nebo auditní orgán využít jako podklad pro tvrzení o nehospodárnosti či neúčelnosti daného opatření.

## Odkazované zdroje

:::{#refs}
:::