---
title: "Co by si měly uvědomit týmy a jejich členové"
editor: source
title-block-banner: true
reference-location: document
citation-location: document
toc-title: "Teze pro týmy"
aliases: 
  - /teze-tymy
format: 
  html: 
    toc-depth: 2
  # pdf: default
  docx: default
---

## Jak tyto vzkazy vznikly

> Strávili jsme spoustu času s šesti analytickými týmy, o něco méně času čtením literatury a zkoumáním zahraniční praxe práce s poznatky. 
>
> Z konfrontace těchto pohledů a zkušeností vykrystalizovala **sada tezí**, o kterých si myslíme, že mohou mnoha lidem ve veřejné správě posloužit při promýšlení vlastní role, role poznatků ve veřejných institucích, i při uvažování o zlepšování vlastní práce.
>
> A myslíme si, že **pokud je budete mít na paměti, bude se vám lépe dařit** při využívání návodů z Průvodce.

## Jak uvažovat o práci s poznatky

### Analytickou práci je třeba chápat široce {#siroce}

Setkáváme se často s tím, že pod pojmem analytická práce lidé vidí především, nebo dokonce pouze, kvantitativní analýzy a jím přidružené aktivity. Tento narativ se snažíme upravit a snažíme se analytickou práci chápat mnohem šířeji. Pracovně proto mluvíme především o práci s poznatky, která zahrnuje také kvalitativní data (desk research, rozhovory, rady a tipy od kolegů atd.).  

### Komunikace je slepou skvrnou -- často právě pro analytiky {#komunikace}

V analytické práci je komunikace zásadním aspektem celého procesu, který bývá často upozaděn. Pokud vyrábíme analytický produkt pro někoho, nebo po nás takový produkt někdo požaduje, je zásadní komunikovat během celého procesu –, již od samotného zadání, jaký problém řešíme, jak a kým bude produkt využíván. Jinými slovy, je zapotřebí pravidelně komunikovat se zadavatelem/příjemcem analýz tak, aby konečná analýza byla využitelná. V prostředí veřejné správy je důležité mít na paměti, že připomínkové řízení není dostatečnou substitucí za kvalitní komunikaci a zpětné vazby k následnému využití analýz a podobných výstupů. 

I proto se v průvodci celá jedna část věnuje [podpoře využití poznatků](/pruvodce/index.hml#vyuziti).

### Neplňte zadání na první dobrou {#zadani}

Analytická práce je ze své podstaty komplexní činností. Často se tedy stáváJedním z důsledků je, že analytici často obdrží nejasná zadání, málo konkretizovaná a bez informací, co má splňovat. Úkolem analytika v takovém případě je především pochopit zadání a to nejlépe tak, že nechá zadavatele zakázky jasně popsat problém, který chce "zákazník" pomocí analýzy řešit. V tomto procesu může zákazník zjistit, že sám nemá tuto otázku jasně definovanou a s pomocí analytika mohou přijít, jak na definici problému, tak identifikaci podkladů pro jeho řešení. 

V průvodci najdete návod [[Zadání analytického úkolu&nbsp;⟶](/pruvodce/zadani-ukolu)]{.btn .btn-resource}

### Specializace nemusí stát za to {#specializace}

Nejen v analytických týmech je pochopitelná tendence navyšování specializace jednotlivých zaměstnanců. Jinými slovy, každý člen týmu se specializuje na konkrétní nástroje, datasety či věcnou tématiku. V tomto ohledu ovšem vzniká dilema, kdy navyšování specializací snižuje možnosti funkčního knowledge managementu. To především pokud dochází k situaci,z toho důvodu, kdy že určitá témata či agenday jsoue v určitý bod natolik v rukou jedné osoby, že jeho případný odchod znamená zásadní zásah do fungování týmu a jeho nabytých zkušeností či znalostí.  

### Velká část znalostí je tacitní {#tacitni}

Experti na využívání a správu znalostí často mluví o tzv. tacitních znalostech (**tacit knowledge**). Tacitní znalosti jsou nezapsané, nekodofikované, nezachycené (narozdíl od znalostí **explicitních**). Často se jedná o znalosti a dovednosti získané praxí, učením se z vlastní práce, pokusem a omylem. Může jít o oblasti práce, které se více než popsatelným postupům podobají řemeslu. 

Většinu tacitních znalostí nemá smysl se snažit **kodifikovat** -- řešením není snažit se sepisovat metodiky a procesní dokumenty. Má ale má smysl snažit se je šířit skrze společnou práci, učení se jeden od druhého, pozorování práce druhých [@lambePrinciplesKnowledgeAuditing2023]. 

Některé **nezachycené explicitní** informace a znalosti (např. kontakty, mentální mapy, některé zavedené postupy) ale má smysl se snažit zachytit -- typicky abychom minimalizovali dopady fluktuace lidí. [TO DO LINK OFFBOARDING]

## Jak uvažovat o dopadu a využití poznatků {#vyuziti}

### Od poznatků ke změně vede více než jedna cesta {#cestypoznatku}

Tvůrci poznatků (analytici, ale nejen) ve veřejné správě často své výstupy vytváří ve vztahu k nějakému **rozhodnutí nebo přímému využití** -- např. analyzujeme nějaký problém, aby někdo jiný podle naší analýzy změnil nastavení nějakého veřejněpolitického nástroje. A pokud se to nestane -- výstup je ignorován, rozhodnutí se odloží, důležití adresáti informace na jejím základě nic neudělají -- vzniká pocit marnosti a frustrace.

Tento přímý, tzv. instrumentální, způsob využití poznatků je důležitý, ale nikoli jediný. A právě ty ostatní způsoby využití poznatků mohou naší práci dát smysl a přínos i ve chvíli, kdy už to nečekáme. Někdy využití poznatků přijde náhodnou konstelací příležostí, někdy se věci dají do pohybu a kdysi udělaná analýza se dá oprášit a může pomoct k lepšímu rozhodnutí. Někdy postupné vkládání vašeho sdělení do různých proudů komunikace přispěje k postupné změně postojů klíčových lidí. Proto dobře o své výstupy a znalosti pečujte (viz návod [Péče o existující znalosti a výstupy](/pruvodce/knowledge-management.qmd)) a snažte se svou práci komunikovat v různých formách a přehledně (viz návody v oblasti [podpory využití poznatků](/pruvodce/index.qmd#vyuziti)). A hledejte příležitosti, kde občas své poznatky znovu předat -- k tomu je zase dobré znát znalostní potřeby své organizace (viz návod [Identifikace znalostních potřeb](/pruvodce/identifikace-znalostnich-potreb.qmd)); v různých částech průvodce pak upozorňujeme na potřebu věnovat se komunikaci a budování vztahů uvnitř i vně vaší organizace.

Prapůvod uvažování o různých módech využití poznatků je práce Carol Weiss [@weissManyMeaningsResearch1979; @weissKnowledgeCreepDecision1980], nedávné empirické upřesnění najdete v @haynesGalvanizersGuidesChampions2011.

### Tvorba politik je často nelineární proces, musíte s tím počítat {#nelinearni}

Dalším častým zdrojem frustrace je neuspořádanost procesů tvorby politik -- zákonů, strategií, opatření, programů. Mnohé příručky pro praktiky i klasické učebnice z oboru *public policy* ukazují lineární, případně úhledně cyklické diagramy, kde se od definice problému přechází k definování řešení, implementaci, evaluaci, a od evaluace zase hezky k redefinici programu. 

Takový model nám může pomoct rozeznat různé typy aktivit v celém procesu, ale málokdy zachycuje skutečnost. Realita nás pak může překvapit a tento nesoulad může paralyzovat naši schopnost generovat užitečné poznatky a ve správný moment s nimi vstupovat do rozhodovacích procesů. 

Pokud se ale sžijete s tím, že politiky a rozhodnutí někdy vznikají nečekaně a skutečný proces nesleduje kroky ideálního postupu jeden za druhým, atd., může vám to pomoct efektivně se procesu tvorby politik účastnit.

Praktické tipy vyvozené z dlouhé řady výzkumů na toto téma nabízí @cairneyHowCommunicateEffectively2017, popř. @cairneyThreeHabitsSuccessful2018. Obrázky pochází z @cairneyPoliticsPolicyAnalysis2021. Silné teze k realističnosti schémat tvorby politik z britské praxe přináší @hallsworthPolicyMakingReal2011 a v českém prostředí toto zkoumají mj. @kohoutekConceptualizingPolicyWork2013.

### Uvažujte o poznatcích a datech ve smyslu stavů (stocks) i toků (flows) {#stocksandflows}

Pro práci s poznatky pomáhá metafora toků a stavů.

**Poznatky jako *tokový jev***: někde pramení, odněkud někam plynou. Tok se někde může zadrhnout a dá se mu pomoct. 

> S tímto obrazem poznatků (zamíchaným do metafory trhu s nabídkou a poptávkou) pracuje koncept tzv. **knowledge brokeringu**: mezi místy, kde poznatky vznikají, a místy, kde se mají využívat, je třeba někoho, kdo zprostředkovává kontakt obou stran: knowledge brokera. Překládá mezi oběma stranami; pro jednu stranu vybírá z toho, co má druhá, a ve vhodné formě a ve vhodný čas poznatky přenáší. Dobře toto zachycuje [@olejniczakLearningEvaluationKnowledge2017; @olejniczakEvaluationUnitsKnowledge2016]; původně koncept pochází z @wardKnowledgeBrokeringMissing2009.

**Poznatky jako *stavový jev***, popř. jako statek, aktivum: poznatky se někde kumulují. Buď je tam necháme ležet nevyužité, nebo o ně budeme pečovat, starat se o to, aby nezchátraly, neztratily se a přinášely užitek i v budoucnosti. A pak se o ně někdo musí starat -- o to, abychom o nich vůbec věděli, dokázali je ve správný moment najít, aktualizovat, využít. Totéž platí o datech -- ledaskdo se stane správcem dat (v neformálním smyslu) aniž by si to uvědomoval. 

Proto v našem průvodci najdete návody pro [péči o již existující znalosti a výstupy](pruvodce/knowledge-management) a [správu dat](pruvodce/data-management).

Jako všechny (nejen fyzikální) metafory a přirovnání i tato místy kulhají, ale v mnohém jsou přesto užitečné.

### Produkty, nejen projekty {#produkty}

TO DO

## Jak uvažovat o změně a zlepšování

### Změna je snazší než se zdá (začni u sebe)

Častou reakcí na podněty ke změnám fungování týmu či postupů práce je odmítavá reakce se slovy, že takto to začít dělat nemůžeme, protože nám to nedovoluje naše prostředí a v něm zaběhlé postupy. Dle našich zkušeností se tato bariéra často zdá mnohem větší než ve skutečnosti je, příklady dobré praxe se pracovišti naopak šíří a je jen zapotřebí tyto příklady zvědomovat a vytvářet. Bariérou jsou i časové kapacity -- často ale platí, že [práce na zlepšení je investicí](#investice).

### Uvažujte o úrovních: individuální, týmová, organizační, systémová

V kontextu zlepšování práce s poznatky se většina praxe, ale také vědecké literatury, zaměřuje na dva hlavní způsoby zlepšení. Prvním je zaměření na jednotlivce. Zde se jedná především o vzdělávání jednotlivců v kapacitách, které vnímáme jako nezbytně nutné pro danou pozici. Většinou je jednotlivec poslán na kurzy, kde má tyto nové kapacity a vědomosti získat. Tím druhým je zaměření na "systém". Tím máme na mysli zaměření na fungování celé organizace/instituce, v našem případě především resorty. Zde se zlepšení zaměřuje na to, jak je daný resort systemizován, jak efektivně a dobře v něm nastavit jednotlivé sekce apd. 

V projektu jsme se snažili pracovat především s úrovní, která se nachází “mezi” těmito dvěma variantami. Tou je tým jako entita, která se společně snaží vykonat určitý úsek práce a je zapotřebí jejich spolupráce k dosažení stanovených výsledků. Bavíme-li se tedy např. o vzdělávání, je dle naší zkušenosti smysluplné dívat se na to, jak můžeme tým vzdělávat společně jako celek tak, aby jejich spolupráce přinesla výsledky práce, které od daného týmu očekáváme. Tento pohled nás taky vede k uvědomění, že technická a metodická zlepšení často [nejsou řešením](#techfixes) daného problému -- alespoň ne úplným. 

### Vyhledávejte a zapojte externí pohled, hlas a pomoc

Z naší externí role a pohledu zpětně vnímáme, že významnou přidanou hodnotu projektu ve spolupráci se zapojenými útvary, byl právě pohled z odstupu. Takový pohled, neovlivněný zaběhlými postupy či přístupy, přináší nadhled a svěží vítr, se kterým je možné vidět určité výzvy a příležitosti jasněji a může výrazně pomoci ke zlepšení práce a fungování týmu. Podobně užitečný může být vlastní pohled z odstupu či společná reflexe daného týmu po určité době. 

### Když chcete něco změnit, může pomoct model chování COM-B

Pro řízení změn v týmu je doporučené nejdříve identifikovat hlavní bariéry, kterým čelí. K tomu může napomoci jednoduchý konceptuální rámec, který vychází z behaviorálních věd [viz @michieBehaviourChangeWheel2011]. Předpoklady pro změnu chování na individuální i týmové úrovni se nachází ve třech oblastech: kompetence a dovednosti pro aplikaci změn, příležitosti pro jejich aplikaci a motivace pro jejich plnění. 

Před návrhem jakýchkoliv změn je tedy vhodné charakterizovat hlavní bariéry pro takovou změnu. Například nedostatek kompetencí a dovedností dělat věci jinak, nedostatek příležitostí dělat věci jinak či nedostatek motivací dělat věci jinak. Po zodpovězení na tyto otázky lze soustředit řízení změn na tyto jednotlivé oblasti, přičemž se mnohé překrývají, a tím i provázejí Například nestačí pouze získat kompetence a dovednosti, ale také najít prostor a příležitosti pro jejich aplikaci. 

### Někdo už to někde řeší

Ať čelíte jakémukoliv problému, je velká šance, že ho někdy někde také řeší, nebo lépe už ho někde někdo vyřešil. Tento triviální poznatek je bohužel často upozaděn, což vede ke zbytečné alokaci času a energie do úkolů, jejichž řešení není potřeba vymýšlet od začátku.

:::{.callout-tip collapse=true}

#### Kam se obrátit (rozbal kliknutím):

- Podívejte se do dobrých praxí v [našich případových studích](/pripadove-studie), případně v odpovídajících návodech
- Poptejte se mezi členy [Pracovní skupiny pro spolupráci analytických útvarů](https://www.cr2030.cz/pracovni-skupina-pro-koordinaci-analyticky-utvaru/)
- Zeptejte se na [Slacku Česko.digital](https://cesko-digital.atlassian.net/wiki/spaces/CD/pages/87457796/Slack), [prohledejte webináře](https://www.youtube.com/@CeskoDigital/videos)
- Podívejte se do [mapy státní správy](/nastroje/mapa)), kde jsou další podobné týmy
- Prohledejte repozitáře studií
  - [Knihovna evaluací ESIF](https://www.dotaceeu.cz/cs/evropske-fondy-v-cr/narodni-organ-pro-koordinaci/evaluace/knihovna-evaluaci)
  - [Knihovna produktů ESF](https://www.esfcr.cz/produkty-opz)
  - [STARFOS od TA ČR](https://starfos.tacr.cz/)
  - [Proběhlé projekty BETA podle resortů](/nastroje/beta)
- Zeptejte se v odborných společnostech -- například [České evaluační společnosti](https://czecheval.cz/)
- Pokud se snažíte zadat zakázku a nevíte, jak něco vyřešit, možná najdete inspiraci v registru smluv (přehledně poskytuje [Hlídač státu](https://www.hlidacstatu.cz/))
- na [KvalitaVS.cz](https://kvalitaVS.cz) najdete přehled dostupných vzdělávacích kurzů a sérii webinářů k různým metodám a nástrojům
- Rozhlédněte se mimo státní a veřejnou správu -- v něčem jsou dobrá města, ledaskdy podobné problémy například v práci s daty řeší akademici a think tanky, experty na některé technologie najdete ve firmách a možná se s vámi o svou expertizu podělí
- Pro technické a datové problémy využijte veřejná fóra -- od Twitteru po [Stackoverflow](https://stackoverflow.com/) a [Reddit](https://www.reddit.com/) (u posledních dvou vyyžijte tagy pro specifické nástroje nebo problémy)
- Některé technologické nástroje a metody mají kolem sebe komunity s komunikačními platformami -- porozhlédněte se
- Rozhlédněte se mimo Česko -- docela bohatě o své práci veřejně [komunikuje](https://www.blog.gov.uk/) britská státní správa a její analytické komunita poskytuje spoustu [návodů, průvodců a příruček](https://analysisfunction.civilservice.gov.uk/)

:::

Ideální by bylo, kdyby toto síťování a sdílení mezi lidmi ve státní správě, kteří pracují na podobných věcech, více a systémově podporovala státní služba, třeba systémem profesí a odborných sítí nebo posílením role tzv. všeobecně uznávaných odborníků. Více najdete v naší sadě [doporučení na systémovou změnu](/doporuceni/systemova-doporuceni.qmd).

### Technické řešení není vždy řešení {#techfix}

Častá tendence v oblasti analytické práce je dívat se na problém tak, že jeho řešení je technické (zavedeme lepší informační systém, vyrobíme dashboardy atd.). Avšak některá z těchto řešení jsou často finančně i časově náročnáé a nakonec ani neřeší původní problém, který jsme se snažili adresovat. Je proto dobré mít na paměti, než se rozhodneme pro technické, že problém a jeho řešení se může nabízet v mnohem méně nákladných alternativách (zlepšení komunikace, lepší definice a porozumění problému, lepší zadání výzkumu atd.).

### Čas strávený zlepšováním vlastní práce je investice {#investice}

TO DO

## Odkazovaná literatura

:::{#refs}
:::