---
title: "Identifikace znalostních potřeb"
subtitle: "Sledujte, co Vaše organizace potřebuje vědět"
blok: ["rizeni"]
poradi: 2
editor: source
aliases: 
  - identifikace-potreb 
---

# O co jde a k čemu to je

Dva hlavní podněty jak začít pracovat na nové analýze jsou dostání úkolu od poptavetele, nebo identifikování znalostní potřeby organizace a analýzu provést na základě této potřeby. Tento popis se zabývá tím, jak tyto znalostní potřeby identifikovat a pracovat s nimi.  

> Při vývoji tohoto návodu jsme se inspirovali vyzkoušenou praxí tzv. Learning Agendas - viz [zdroje](#další-zdroje) na konci návodu.

# Sebediagnostika: je to pro mě?

- Jste vedoucím či členem analytického oddělení?
- Jste zastupce odborného garanta v programu BETA?
- Máte zájem o to, aby se Vaše ministerstvo více staralo o své znalostní potřeby?

:::{.strip .page-columns .page-full}

:::{.aside}
<br>
:::

# Jak na to

## 1. Ptejte se poptavatelů analýz

V kontextu dialogu s poptavateli analýz se ptejte na analýzy, které by do budoucna chtěli uskutečnit 

Především propojujte výzkumné potřeby s jednotlivými agendami - oddělení X potřebu vědět Y pro agendu Z.

Podobně v kontextu jednotlivých výzkumných projektů mohou vyvstat nové výzkumné potřeby - zaznamenávejte i ty.

## 2. Dialog strukturujte pomocí mapy agend a potřeb

:::{.aside}

**Ukázka takové plachty agend a její vysvětlení**

<br>

:::{.btn .btn-resource}
[Stáhnout](attachments/Plachta agend - web verze.docx)
:::
:::

Pro strukturovaný dialog o výzkumných potřebách jsme vytvořili tzv. plachtu agend, která má sloužit k uchování jednotlivých agend a na ně vázaných výzkumných potřeb. 

Plachta má např. umožnit roztřídění výzkumných potřeb na ty, které se naplní interními kapacitami (analytické, evaluační oddělení atd.) či externími kapacitami (programy BETA, SIGMA, veřejné zakázky)

##  Co s potřebami

Jakmile se s uživateli dohodnete, co a kdy potřebují, mohou vám přijít vhod další návody:

- [Zadání analytického úkolu](zadani-ukolu)
- [Zadávání výzkumu BETA](beta)
- [Zadávání externího výzkumu](zadani-vyzkumu)

Někdy se stane, že něčí otázku dokážete zodpovědět pomocí už hotového výzkumu. Na to se ale potřebujete dobře starat o už udělané studie a analýzy [⟶ návod Péče o hotové analýzy](knowledge-management).

:::

# Na co si dát pozor aneb tipy & triky

Tento proces vyžaduje ideálně velké zapojení mnoha stakeholderů na ministerstvu. Je určitě výzvou najít ideální balanc mezi získávání relevantních informací a přehlcením požadavků na stakeholdery. Nejdůležitější je, aby stakeholdeři chápali a především viděli, že celý proces je nakonec pro jejich benefit a jejich ulehčení práce. 

# Další zdroje

[Making Federal Agencies Evidence-Based](https://www.businessofgovernment.org/sites/default/files/Making%20Federal%20Agencies%20Evidence%20Based.pdf)
