---
title: "Péče o existující znalosti a výstupy"
subtitle: "Podpořte využití svých analytických výstupů"
blok: ["vyuziti"]
poradi: 8
editor: source
aliases: 
  - knowledge-management
---

# O co jde a k čemu to je

Jak se starat o hotové analýzy tak, aby byly využité a měly patřičnou životnost? Analytici často přemýšlí hlavně nad kvalitou analýz, ale důležitá je i jejich využitelnost či dohledatelnost analýz po delší době od jejich publikace.

Bez přehledného uchování a zpřístupnění existujícího poznání organizace plýtváme prostředky. Bez podpory využití ztrácíme hodnotu toho, co někdo odpracoval.[^1]

[^1]: Pracujeme tedy s pojmem knowledge management spíše v užším slova smyslu. V širším pojetí téma představují některé publikace odkazované v [dalších zdrojích níže](#další-zdroje). A aby to nebylo tak jednoduché, někdy pod pojmem *knowledge management* najdete celé téma práce s poznatky, viz např. @toppKnowledgeManagementPolicy2018.

:::{.callout-note}
Nápady v tomto návodu jsme během projektu neměli možnost vyzkoušet. 

Vznikly ale jako reakce na skutečné potřeby jednoho ze zapojených týmů a reflektují dobré praxe z dalšího z nich. 

Pokud něco vyzkoušíte, [dejte nám o tom vědět!](/pribeh-projektu#kontakt)
:::

# Sebediagnostika: je to pro mě?

- Jste zpracovatelem analýz, které mají využít lidé mimo Vaše oddělení?
- Ptají se vás lidi, co přesně děláte a mají o Vaši práci zájem? 
- Máte odpovědnost za to, aby se analýzy využívaly?
- Stává se Vám, že se lidé ptají na otázky, které jsou již zodpovězené v předchozích analýzách?

:::{.strip .page-columns .page-full}

# Jak na to

K tomu, aby se analýzy více využívali jsou potřeba tři základní prvky: **zachycení a katalogizace, zpřístupnění a propagace**.

> Slovem analýza tady myslíme jakýkoli uchovatelný výstup práce s poznatky -- podklad, studie, dokument, tabulka, dataset, dashboard...

Jaké postupy zvolíte v jednotlivých krocích by mělo vycházet z **vašeho porozumění potřeb uživatelů analýz**. 

- Komu potřebujeme přístup k analýzám usnadnit? 
- Co potřebují? Co je nejvíc trápí? 
- Co zvládnou? 

Pokud nevíte, ptejte se. (Systém katalogizace a zpřístupňování analýz je svého druhu interní produkt a na jeho vývoj tedy můžete použít postupy uživatelského výzkumu a testování viz&nbsp;⟶ [návod](LINK TODO)).


## 1. Zachycení a katalogizace analýz

- Vytvořte si klidně i jednoduchou tabulku/seznam všech analýz
- Lze také propojit s "plachtou agend" viz [tento průvodce](/pruvodce/identifikace-znalostnich-potreb), která může sloužit k určení analytických potřeb organizace
- V sofistikované variantě můžete výstupy zanášet do tzv. knowledge (gap) map, neboli mapy znalostí a znalostních mezer. To ale vyžaduje hlubší práci na tom, jaké rozměry věci chcete v mapě zachycovat.
- Souvisí s [přehledem analytických úkolů](/pruvodce/prehled-analytickych-ukolu), ale jeho účelem je plánovat práci 


## 2. Zpřístupnění analýz

- Sharing sessions/workshopy - setkání, kde můžete diskutovat o dostupných analýzách a jejich využití 
- V [programu BETA](/pruvodce/beta2) role zástupce odborného garanta -- jeho role je starat se o naplňování vědomostních potřeb ministerstva
- Vytváření různých typů výstupů pro různé cílovky -- někteří stakeholdeři potřebují výstupy v různých formách, zkuste poznatky předávat podle jejich potřeb
- Syntéza poznatků z různých výzkumů - policy stewardship 

Moment zachycení, zdokumentování a zpřístupnění výstupů lze zapracovat do interního postupu k uzavření projektu.

Doporučujeme vytvořit kromě samotného přehledu také **standardizovanou strukturu pro ukládání a organizaci analýz**. Je vhodné vytvořit pro každou analýzu samostatnou složku, která bude rozdělena do dalších podsložek stejných pro každýb projekt (například 01. Zadání - kontext, 02. Data, 03. Analýza, 04. Výstupy). To usnadní přehlednost a umožní strukturovaně uchovávat veškeré potřebné informace související s každou provedenou analýzou. (Více viz návod [Péče o již existující poznatky a analýzy](knowledge-management.qmd)).

## 3. Propagace analýz

Můžete použít třeba následující kanály a formáty:

- Newsletter: udělejte vlastní, nebo napište příspěvek do již existujícího
- Videa: zajímavé animované video, ale také jen nahrávky důležitých schůzek (např. kontrolní dny v programu BETA)
- Intranet: sdílejte zajímavosti, které mohou lidi vést k otevření analýzy
- Poraďte se s vaším PR/komunikačním oddělením, jak danou analýzu lépe propagovat (i interně)
- Pravidelné okénko na poradě
- Obědové semináře

:::{.callout-tip}

#### FAIR principy

Pro správu výstupů se může hodit myslet na stejné principy, které se uplatňují při správě dat, tzv [FAIR principy](https://www.go-fair.org/fair-principles/):

- Findable: daná věc musí jít najít
- Accesible: musí se dát k ní dostat
- Interoperable: u dat zásadní, ale i u výstupů musí být jasné, jak souvisí s jinými
- Reusable: ideálně je možné výstup nebo jeho část dále použít, navázat na něj, rozvinout

:::

:::

# Na co si dát pozor aneb tipy & triky

Kvalitní knowledge management **není jen o různých technických a procesních opatřeních, ale především o komunikaci**. Databáze nebo nový informační systém sám o sobě knowledge management nezachrání, ale může Vás stát hodně času a energie. 

Pokud se pustíte do katalogizace, mějte na paměti, že důležitější je mít **něco základního** -- klidně jednoduchý excel nebo seznam na intranetu -- než mít sofistikovanou databázi, kterou nikdo nebude udržovat.

V kontextu propagace je dobré si uvědomit, že **ne vše jde naplánovat**, využití poznatků se často děje v tzv. windows of opportunity. V [tezích pro týmy](/teze-tymy) vysvětlujeme, že [poznatky nejsou vždy využity hned a když to čekáte](/teze-tymy#cestypoznatku), často mají nepřímý dopad. Součástí této práce tedy je také monitoring příležitostí, kde může nějaký poznatek nebo výstup, který už máme, vstoupit do živého tématu nebo řešení nějakého aktuálního problému v tématu nebo organizaci.

Sebelepší propagace ale věc nezachrání, pokud analýzy nevychází ze **skutečných potřeb** (⟶ návod [Identifikace znalostních potřeb](identifikace-potreb)) nebo trpí špatným **procesem zadání** mezi zákazníkem a tvůrcem (⟶ návod [Zadání analytického úkolu](zadani-ukolu) & návod [Zadání externího výzkumu](zadani-externiho-vyzkumu)).

A pamatujte, že i po zavedení skvělého knowledge managementu bude stále platit, že [**část znalostí je pouze v hlavách lidí**](/doporuceni/teze-o-praci-s-poznatky-tymy.qmd#tacitni) a je potřeba zajistit jejich zachování např. i když někdo tým opouští (⟶ návod [TODO LINK Offboarding člena týmu](offboarding)).

# Další zdroje

TODO

[What is Knowledge Management](https://www.starmind.ai/resources/what-is-knowledge-management-and-why-is-it-so-important) [@starmindaiWhatKnowledgeManagement2022]

[Knowledge Management in the Public Sector](https://www.semanticscholar.org/paper/Knowledge-Management-in-the-Public-Sector-Malik-Al-Toubi/59b93fd7ecf3e8f8f2027d7b68cfa12a5f05fbd9) [@malikKnowledgeManagementPublic2018]

[@zappWorldBankEducation2017]

[@lambePrinciplesKnowledgeAuditing2023]

[@bankWorldBankKnowledge2019]

[Knowledge Solutions](https://link.springer.com/book/10.1007/978-981-10-0983-9) [@serratKnowledgeSolutions2017]

Pro správu znalostí v projektech se vám může hodit manuál nebo některé z nástrojů vyvinutých na Masarykově univerzitě v projektu [Řízení znalostí v projektech](https://pkm.econ.muni.cz/).

[](https://cesko.digital/events/jak-usporadat-informace-a-usetrit-cas-a-naklady)

## Odkazovaná literatura

:::{#refs}
:::
