---
title: "Tvorba nástroje veřejné politiky"
subtitle: "Jak lépe připravovat dotační výzvy a podobné instrumenty"
blok: ["metody"]
poradi: 7
editor: source
---

# O co jde a k čemu to je

Tento návod se zabývá zlepšením a zefektivněním přípravy nástroje veřejné politiky, jako jsou například:

- dotační výzvy
- dotační programy
- programy podpory
- návrhy politik a strategií 

:::{.callout-tip}

Vycházíme ze dvou poznatků:

1. Týmy ve státní správě často tvoří podobné nástroje veřejné politiky (*policy making*), ale někdy si ani neuvědomují, že jde o specifickou disciplínu [^1]
1. Pro tento typ práce neexistuje v českém prostředí dobrá metodická podpora. 

[^1]: s výjimkou tvorby strategií, pro kterou sice existuje metodika, ale jde o relativně specifickou činnost.

:::

Účelem tohoto návodu není tyto činnosti kompletně definovat a metodicky uchopit, ani nahradit existující metodiky tvorby např. výzev v EU fondech. 

Spíše chceme upozornit na nejčastější nepochopení a nástrahy, se kterými se týmy potýkají, a usnadnit komukoli se s nimi popasovat bez ohledu na to, zda je o dotační program, výzvu v EU fondech, nebo jiný typ nástroje.

:::{.aside}

**Případové studie**

Tento návod jsme vyvinuli a testovali ve spolupráci s oddělením rovných příležitostí ESF MPSV.

<br />

:::{.btn .btn-resource}
[Číst případovou studii](../pripadove-studie/mpsv)
:::

:::

# Sebediagnostika: je to pro mě?

Návod je vhodný pro týmy v těchto situacích:

- Jejich pracovní agenda se obvykle neskládá z přípravy nástrojů veřejné politiky (tj. nejde např. o strategické týmy nebo týmy přípravy výzev EU fondů)
- Nedisponují dostatečnými lidskými kapacitami (především znalosti metod, postupů atd.) ani časovými možnostmi 
- Nemají vyjasněné zadání zeshora 
- Není jasná definice toho, k čemu má daný nástroj mířit
- Nedisponují dostatečnou datovou podporou

<br>

:::{.strip .page-full .page-columns}

# Jak na to 

## 1. Principy a základní rady

1. Rozfázujte si proces a nepředbíhejte
1. Analýza neznamená popsat všechno
1. Začněte u cílových skupin
1. Stavte na tom, co už se o problému a řešeních ví
1. Rozšiřte si pole možných řešení
1. Včas se zamyslete, jak budete váš nástroj vyhodnocovat

## 1. Vyjasněte zaměření a cíle nástroje

#### a. Rešerše relevantní odborné literatury 

#### b. Získat základní konceptuální pochopení intervenční logiky -- Jak má nástroj veřejné politiky docílit změny

  - i. Zdroje DOPLNIT

- c. Rešerše k empirické problematice

 - d. Vyjasnění cílové skupiny
  - i. Na koho nástroj míří?
  - ii. Co o cílové skupině víme?

e. Vyjasnit si problém: Co víme o problémech, který má výzva adresovat?

  i. Rešerše literatury
  ii. Konzultace s odborníky a odbornicemi
  iii. Jaké jsou příčiny problémů?
  [možná inspirace](https://www.mindmapping.com/)

f. Vyjasnění si řešení: Čeho chceme dosáhnout?

  i. Identifikovat rozdíl mezi současnou realitou a kýženým stavem
  ii. Jak se dostaneme ke kýženému stavu?
  iii. Co už se zkoušelo?
  iv. Co fungovalo v jiných kontextech?

g. Jaké konkrétní postupy budou v rámci nástroje implementovány?

h. Vypracování intervenční logiky


## 2. Záměr nástroje

  a. Interní dokument, který v krátkosti představuje problematiku a cíle a metody nástroje
  b. Vypracování prvního draftu 
  c. Interní připomínkování draftu
  d. Konzultace draftu s odborníky a odbornicemi
  e. Připomínkování ze strany vedení

## 3. Příprava budoucí evaluace

  a. Seznámení se s principy, cíly a metodami evaluace
  b. Konzultace s interní evaluační jednotkou (pokud taková existuje), případně externími odborníky a odbornicemi 
  c. Vydefinování cílů evaluace
  d. Zanesení mechanismů (budoucí) evaluace do záměru nástroje a jeho vypsání 

## V čem může pomoci účast externích spolupracovníků? 

  a. Moderace a facilitace interních workshopů k problematice
  b. Strukturování nápadů a debat 
  c. Feedback na drafty jednotlivých dokumentů

:::




# Tipy a triky

  a. Zkušenosti ukazují, že je důležité přípravu intervenční logiky nepodcenit, jelikož se pak propisuje do všech dalších kroků 
  b. Záměr nástroje je nápomocný v definici celkové problematiky a jejího vyjasnění si uvnitř týmu
  c. Stejně tak evaluaci nástroje je nutné řešit již v průběhu formulace, aby bylo možné do designu nástroje zanést evaluační mechanismy 
  d. Kolektivní brainstorming a připomínkování 
  e. Vhodná je přítomnost někoho externího, pokud existuje ta možnost

# Další zdroje

## Rámce pro tvorbu opatření a strategií

Better Regulation Toolbox

NZ Policy Making Toolkit

## Nástroje pro inspiraci a sebehodnocení

@olejniczakComparingBehavioralAssumptions2020

@michieBehaviourChangeWheel2011

@instituteforgovernmentEvidenceTransparencyFramework2015

## Inovace a rozšíření

Design thinking, karty

Open policy

## K zamyšlení



## Rozvojové příležitosti

Ministerstvo pro místní rozvoj nabízí [vzdělávací program Strateduka](https://mmr.gov.cz/cs/microsites/portal-strategicke-prace-v-ceske-republice/strategicke-projekty/strateduka), který vás problematikou tvorby politik, strategií a nástrojů provede komplexně.

## Odkazovaná literatura

:::{#refs}
:::