---
title: "Inventura analytických úkolů"
subtitle: "Jak mít přehled v tom, co všechno děláte"
blok: ["rizeni"]
poradi: 8
editor: source
aliases: 
  - inventura
  - prehled-ukolu
---

# O co jde a k čemu to je

Zvláště analytické týmy, které dělají větší množství dílčích i větších analýz, pravidelně či ad hoc a poptávku, často hledají, jak svou práci zefektivnit: některé analýzy zredukovat, některé zautomatizovat, u některých zapracovat na tom, aby je zvládli i neanalytici v organizaci.

A také pomoct tomu, aby lidé v organizaci dokázali využít již existující výstupy nebo z nich vyjít při definování své potřeby.

K tomu všemu může posloužit inventura analýz.

Ačkoli příklady v tomto návodu budou nejlíp sedět na datově analytickou práci, postupy lze snadno vztáhnout na jakýkoli typ generování poznatků a podkladů na poptávku.

:::{.aside}

**Případové studie**

Tento návod jsme vyvinuli a testovali ve spolupráci s analytickým oddělením TA ČR.

<br />

:::{.btn .btn-resource}
[přečíst případovou studii](../pripadove-studie/tacr)
:::

:::

# Sebediagnostika: je to pro mě?

Kdy se může přehled vzešlý z inventury hodit?

- Dostáváme příliš ad hoc opakujících se poptávek, jejichž odpovědi lze najít v našich předchozích výstupech?
- Máme ambici lépe plánovat a prioritizovat práci -- případně i v diskusi s vedením organizace a poptavateli analytické práce
- Zvažujeme, jestli některé analýzy dokážeme zautomatizovat nebo jestli je má smysl převádět např. na dashboardy

:::{.strip .page-columns .page-full}

# Jak na to

:::{.aside}

**Ukázka přehledu analýz**

<br>

:::{.btn .btn-resource} 
[Stáhnout](attachments/Prioritizace analýz.xlsx)
:::
:::

## 1. Identifikujte smysluplné kategorie pro vytvoření přehledu

Kolegové z analytického oddělení doporučují nepřesáhnout více jak tři kategorie podle kterých analýzy řadit

V našem případě jsme měli 15 kategorií, což se ukázalo jako nejen problematické z hlediska počtu jako takového, ale také pro srozumitelnou komunikaci dalším analytikům, kteří nebyli u procesu vzniku přehledu

## 2. Navrhněte strukturu přehledu

Cílem je mít přehled udělaný tak, aby byla pochopitelný i pro zbytek organizace a dalo se v něm lehce vyhledávat. 

a. To nejen pro členy analytického oddělení, ale také pro jeho zákazníky, kteří by přehled měli využívat.

b. Zde doporučujeme přizvání několika archetypů těchto zákazníků do procesu vytváření, aby jejich zpětná vazba mohla být součástí finálního produktu. Při designu je také zapotřebí mít na paměti potenciální růst celého přehledu, který v čase může významně překonat současnou velikost. 

## 3. Zaneste jednotlivé činnosti do přehledu

Pokud historicky existuje velké množství analýz, doporučujeme doplnit přehled např. za poslední rok a pak postupně doplňovat nově vzniklé analýzy (tzv. from now on). 

Historické analýzy pak můžete doplňovat, když budou zrovna relevantní.

## 4. Reflexe

Zamyslete se, jak s přehledem pracovat dále, kdo se o něj bude starat apod.

Kromě samotného zachycení pro potřeby ostatních vám přehled také může posloužit k:

- úvahám nad potenciálem automatizace některých analýz či jejich převedení do formy **datového produktu**, např. dashboardu -- viz návody [Testování webového produktu ->](user-testing.qmd) a [Práce s daty moderně ->](analyza-dat.qmd)
- prioritizaci např. i v diskusi s vedením nebo poptavateli analytické práce
- plánování práce v týmu i napříč organizací
- identifikace dovedností, které můžete rozšířit do organizace a snížit tím počet poptávek po rutinních analytických úkonech -- viz i návody [Vyhledání veřejných dat ->](vyhledani-dat.qmd), [Práce s daty moderně ->](analyza-dat.qmd) a [Rešerše literatury ->](prehled-literatury.qmd)
- zefektivnění momentu zadávání/přebírání analytických úkolů -- viz návod [Zadání analytického úkolu ->](zadani-analytickeho-ukolu.qmd)

## 5. Vyjasněte si komunikační plán přehledu 

Důležitou funkcní přehledu je podat informaci ostatním částem organizace o tom, jaká práce se již udělala, co tedy lze využít a na co navázat.

a. Pokud chceme, aby přehled využívali všichni relevantní stakeholdeři, je důležité, aby se o jeho existenci dozvěděli. Je rozumné konzultace např. i s PR oddělením organizace nebo kýmkoli, kdo se stará o interní komunikaci.

b. Doporučujeme vytvořit zjednodušenou verzi přehledu, která se zpřístupní k využití pro běžného uživatele.

:::

# Na co si dát pozor aneb tipy & triky

Zásadní je především **design přehledu**, ten musí umožnit všem stakeholderům přehlednou práci. Přehled by měl být nadesignován tak, aby se s ním dalo pracovat dlouhodobě (tedy aby nezapadl), především při zachycování mnohem většího počtu informací či z při předání správy přehledu novému člověku.

Doporučujeme vytvořit kromě samotného přehledu také **standardizovanou strukturu pro ukládání a organizaci analýz**. Je vhodné vytvořit pro každou analýzu samostatnou složku, která bude rozdělena do dalších podsložek stejných pro každýb projekt (například 01. Zadání - kontext, 02. Data, 03. Analýza, 04. Výstupy). To usnadní přehlednost a umožní strukturovaně uchovávat veškeré potřebné informace související s každou provedenou analýzou. (Více v návodu [Péče o již existující poznatky a analýzy](knowledge-management.qmd)).

