---
title: "Uživatelský výzkum pro analytické výstupy"
subtitle: "Výstupy a reporty, které fungují pro uživatelé"
categories: ["Pro analytiky", "Design"]
blok: ["vyuziti"]
title-block-categories: false
poradi: 11
editor: source
nocite: |
  @dittrichBegInnerGuide
  @richardsContentDesign2017
  @downeGoodServicesDecoding2020
---

# O co jde a k čemu to je

Součástí práce analytika je umět své výsledky předávat uživatelům v přístupném, přívětivém a zejména užitečném formátu. Cílem je podpořit využitelnost výstupů.

Ať už se jedná o report, výroční zprávu, webovou stránku nebo dashboard, je důležité pochopit potřeby potenciálních uživatelů již ve fázi přípravy a návrhu analytického výstupu.

A před vypuštěním do světa je užitečné výstup otestovat a zjistit, zda skutečně naplňuje očekávání a potřeby, přičemž nevznikají na straně uživatele překážky k jeho využití. 

# Sebediagnostika: je to vůbec pro mě?

- Produkujete analytické výstupy (reporty, weby, studie), které mají být využívány jinou skupinou lidí  
- Máme signály, že potenciál pro využití výstupu není naplněný
- Máme zpětnou vazbu od uživatelů, že výstup není přehledný

V případě tvorby webového produktu je také důležité zajistit abychom:
- měli dostatečnou kapacitu na to, abychom realizovali uživatelský výzkum ještě než se zadají specifikace developerům
- měli možnost po spuštění webu provádět změny na základě uživatelského testování? Do jaké míry? Za jaké náklady


:::{.aside}
<br>
:::


:::{.callout-tip}

### Různá využití: report, výročka, web...

Postup pro realizaci uživatelského výzkumu jsme aplikovali na čtyřech případech:

**[Výroční zpráva o státní službě](https://www.mvcr.cz/sluzba/clanek/vyrocni-zprava-vyrocni-zprava-o-statni-sluzbe.aspx)**: Ministerstva vnitra každý rok přináší přehled o vývoji státní služby v ČR. Jejím cílem je poskytnout žádané infromace rozmanité  skupině čtenářů. 

**Tematický report [INKA](https://inkaviz.tacr.cz/data/INKA-3-Souhrnna-a-doporucujici-zprava.pdf)**, který vydáva Technologická agentura ČR, shrnuje zjištění z dotazníkového šetření mezi podniky ohledně jejich inovačních kapacit. 

**Výsledky dotazníkového šetření oddělení rovnosti mužů a žen (MPSV)** slouží pro žadatele o podporu jako podklad pro jejich rozhodování. Jedná se tak o úzkou a specifickou skupinu čtenářů, kteří mají na základě těchto výsledků učinit rozhodnutí. V tomto případě vstupoval uživatelský výzkum již do fáze designu dotazníku. 

**Webu [strategie RIS3](https://www.ris3.cz/)** spravovaný MPO. Vedle naplnění potřeb uživatelů byla v tomto případě důležitá i přívětivost a funkčnost webového rozhraní, se kterým interagují uživatelé.

:::

:::{.aside}

<br>

**Případové studie**

Tento návod jsme vyvíjeli s několika týmy (viz box vlevo):

<br>

:::{.btn .btn-resource}
[Tým S3 na MPO →](/pripadove-studie/case-mpo.qmd)
:::

<br>

:::{.btn .btn-resource}
[TA ČR →](/pripadove-studie/case-tacr.qmd)
:::

<br>

:::{.btn .btn-resource}
[MPSV →](/pripadove-studie/case-mpsv.qmd)
:::

:::

:::{.page-full .strip .page-columns}

# Jak na to?

## 1. Definujte záměr uživatelského výzkumu

- Definujte si vaši designerskou výzvu. Například: 
  - jak bychom mohli zajistit, aby uživatelé snadno našli žádané informace
  - jak bychom mohli zajistit, aby uživatelé snadno interagovali s webovou stránkou a plnili specifické úkony

## 2. Popište, kdo jsou potenciální čtenáři a uživatelé (uvnitř či mimo vaši organizaci)	

- Vytvořte seznam lidí, kteří budou dotazováni v dalších krocích
- Vytvořte typického uživatele
- Oslovte 3 až 5 potenciálních uživatelů, kteří spadají do různých skupin na cca 30minutový rozhovor a položte jim následující otázky:
  - Pro jaké účely byste využil/a daný výstup?
  - Jaká máte očekávání od takového výstupu?
  - Specifikujte jejich motivace, obavy a potřeby pomocí nástroje [Value Proposition Canvas - viz níže](#vpc) 


## 3. Pro každou skupinu popište:

- Co mají dělat pomocí vašeho výstupu / Jaké další činnosti budou navazovat?
- Jaké informace jsou nejdůležitější a jaké jsou vedlejší, případně co může ještě podpořit využití
- Co jim může bránit v jeho využití

## 4. Vyhodnocení a testování 

- Vyhodnoťte závěry uživatelského výzkumu pro tvorbu formy a obsahu vašeho analytického výstupu a vytvořte první prototyp. Ten můžete následně otestovat a ověřit, že výstup plní jejich očekávání. 

- Po provedení změn znovu otestujte analytický výstup s uživateli, abyste zjistili, zda byly provedené změny účinné.

# Testování webu

## 1. Pobavte se s uživateli

Příprava:

- Vytvořte sadu témat, které chcete od uživatelů zjišťovat.
- Připravte sadu úloh (1 až 3), které uživatel bude vykonávat během testování. Nachystejte si přesné instrukce
- Připravte si sadu hypotéz ohledně toho, jaké překážky mohou vzniknout.

Realizace rozhovoru:

- Na začátku respondentovi vysvětlete, jak jeho vstupy použijte a hlavně ho ujistěte, že testujete web, nikoli jeho schopnosti
- V první části rozhovoru se zeptejte respondenta, jaké úlohy hodlá dělat a proč.
- Zadejte 1 až 3 předem připravené úlohy
- Pozorujte, jak úlohy realizuje respondent (tazatel nezasahuje, pouze pozoruje)
- Ve třetí části udělejte debrief 

## 2. Vytvořte feedbackový dotazník

Příprava:

- Zvolte sadu otázek (System Usability Scale nebo UMUX) a škál pro odpovědi (většinou 1 až 5).
- Vytvořte dotazník např. v Google Forms.
- Rozhodňete si, zda dotazník bude distribuován přímo na stránkách pomocí prosby o feedback nebo cíleně přes email.

## 3. Syntéza výsledků

- Popište skupiny uživatelů, jejich charakteristiky a potřeby.
- Sepište identifikované překážky a popis jejich příčin.
- Prioritizujte problémy dle palčivosti a proveditelnosti řešení.

:::

# Tipy a triky, aneb na co si dát pozor

- Na průzkum lidé nemají moc času, snažte si uvědomit, jak je nezahltit, nikdy nenaplníme potřeby všech. Můžeme se dozvědět, že analytický výstup je zbytečný děláme ho špatně/nevyužitelně
- Není potřeba provést rozhovory se všemi možnými uživateli, stačí 3-5 lidí, kteří pokrývají širší spektrum potenciálních uživatelů
- Dejte zpětnou vazbu dotázaným lidem, aby věděli, jak jste zapracovali jejich podněty
- Uživatelský výzkum by měl být kontinuální proces. Na základě nových zjištění a feedbacku od uživatelů pravidelně aktualizujte a vylepšujte analytický výstup.
- Během rozhovoru je důležité nenavádět uživatele a neposkytovat mu rady.
- Vždy vysvětlit respondentům, že testujeme design webu a ne jejich schopnosti.


# Další zdroje a literatura

## Value Proposition Canvas {#vpc}

Pro každou cílovou skupinu popsat v následujícím pořadí:

- Potřeby: co je motivuje k využití našich služeb?
- Motivace: čeho chce náš uživatel dosáhnout? Jakou potřebu mu uspokojujeme?
- Obavy: co jim brání ve využití našich služeb?
- Popis nabízených služeb: jaké služby nebo produkty jim nabízíme, abychom uspokojili jejich potřeby?

Více k Value Proposition Canvas na [webu 100 metod](https://kisk.phil.muni.cz/100metod/value-proposition-canvas)

## Sada otázek pro dotazníkové šetření k webovému produktu

System Usability Scale

  1. Věřím, že většina lidí se naučí používat tento systém velmi rychle.
  2. Systém mi připadal zbytečně složitý.
  3. Myslel(a) jsem si, že používání systému bylo snadné.
  4. Myslím si, že bych potřeboval(a) podporu technické osoby, abych mohl(a) tento systém používat.
  5. Funkce v tomto systému byly dobře integrovány.
  6. Myslel(a) jsem si, že v systému bylo příliš mnoho nesourodosti.
  7. Představuji si, že většina lidí se naučí používat tento systém velmi rychle.

Více na [webu 100 metod](https://100metod.cz/post/157274192704/93-system-usability-scale)

UMUX

  1. Moje požadavky jsou splněny schopnostmi tohoto systému.
  2. Naučit se používat tento systém je snadné.
  3. Musím se naučit mnoho věcí, než budu moci tento systém používat.
  4. Práce se systémem je nepohodlná.
  5. Úkoly mohu efektivně dokončovat pomocí tohoto systému.
  6. Potřeboval(a) bych hodně času, abych se zvykl(a) na tento systém.
  7. Funkce systému jsou dobře integrovány.

Více např. na [webu MeasuringU](https://measuringu.com/umux-lite/)

## Další zdroje

:::{#refs}
:::

<br>

[UK GOV. User research -- Service Manual -- GOV.UK](https://www.gov.uk/service-manual/user-research)  

[Design systém gov.cz](https://designsystem.gov.cz/#/) & [Pravidla pro tvorbu obsahu](https://designsystem.gov.cz/#/pravidla/pravidla-pro-tvorbu-obsahu)

[MUNI-KISK (2015). 100 metod](https://100metod.cz/) 

[Norman Nielsen: Usability Testing 101](https://www.nngroup.com/articles/usability-testing-101/)
