---
title: "Vizualizace dat"
subtitle: "Jak zobrazit data tak, aby se na to dalo dívat"
description: "Dobré praxe, tipy a hlavně návod, jak vylepšit své datové vizualizace"
categories: ["Komunikace", "Kvanti"]
blok: ["vyuziti"]
title-block-categories: false
editor: source
---

# O čem to je

Před vypuštěním jakékoliv vizualizace dat do světa je dobré otestovat, zda je srozumitelná a pochopitelá.

Vizualizace je datový produkt a tak k němu můžete přistupovat.      
- Chápat, kdo jsou uživatelé  
- Vcítit se do jejich situace  
- Zjišťovat (nebo aspoň odhadovat), co potřebují  
- Produkt dělat podle potřeb uživatelů  
- Produkt před vypuštěním do světa otestovat  
- Pak sbírat zpětnou vazbu a iterativně zlepšovat  

# Případová studie

Tuto intervenci jsme aplikovali s týmem OVE na MMR

# Sebediagnostika: je to pro mě?

- Máme signály o tom, že nemáme optimální vizualizace?
- ...

# Jak na to

## Vcíťte se do čtenáře 

**Vytvořte karty uživatelů**

- Kdo to je, jaký*á je, co dělá? (jméno, věk, role, vzdělání, postoje, …)
- Čeho potřebuje dosáhnout? (sepsat analýzu / přesvědčit paní X / vysvětlit téma T, …)
- Co ho*ji trápí, čemu čelí, s čím se potýká (“Jsem busy” / “Nerad čtu data” / “Špatně vidím”)
- Co chce od vizualizace dat
  - Forma: přehled vs. detail, standard vs. inovace, …
  - Účel: Zaujmout, přesvědčit, prozkoumat, hledat vzorce…

!


## Definujte sdělení

### Tabulka nebo graf?

**Tabulka**

- Porovnat údaje (point in time, území, skupiny)
- Poskytnout hodnoty a měření (frekvence/počty, procenta/podíly, indexy)
- Poskytnout souhrnné údaje (součty, průměry)
- Zobrazit hodnoty velmi rozdílných velikostí (např. tisíce vs. miliony)

**Graf**

- Zobrazit vzorce/pravidelnosti (sezonalita) 
- Zvýraznit trendy (vývoj v čase)
- Ukázat vztahy (korelace, kauzality)

### Grafy: čáry, body, sloupce, koláče

**Statistické souvislosti**

- Sloupcový
  - distribuce
  - řazení
  - deviace
  - magnituda
  - časová řada
- Čarový
  - časová řada
  - korelace
- Koláčový:  
  - část celku
- Bodový:  
  - korelace

**Další prvky grafů**

- Anotační vrstva
- Osy, škály, legendy  
- Nedatové prvky (vodítka, pozadí)
- Titulek a podtitulek
  - Titulek = hlavní sdělení grafu: “Nárůst počtu uchazečů o zaměstnání”
  - Podtitulek: = popis datové sady, území a časového úseku: “Vývoj počtu uchazečů o zaměstnání v Praze v období 2010-2022”
- Zdroj  

## Použijte checklisty

:::{.callout-note title="Checklist" collapse=true}

{{< include vizualizace-checklist.qmd >}}

:::{.btn .btn-primary}
[Stáhnout checklist ve wordu](vizualizace-checklist.docx)
:::

---

:::

## Otestujte srozumitelnost a pochopitelnost grafu

### Otestujte graf na sobě:

- *Jak bych popsal/a graf nebo tabulku po telefonu?*

### Testujte graf **na ostatních:**  

- Čtení: *Ukážu ti graf, komentuj prosím průběžně nahlas, jak ho postupně čteš, jak nad ním přemýšlíš, čemu nerozumíš, co si odvozuješ.*
- Sdělení: *Projdi si, prosím, graf a zkus identifikovat, co je jeho hlavní myšlenkou, sdělením.*

Pokuste se taky ukázat někomu graf na pouhých 5 vteřin a zeptejte se, co je jeho hlavní myšlenkou. 


# Další zdroje

