---
title: "Zadání analytického úkolu"
subtitle: "Jak komunikovat se zadavatelem analytického úkolu"
blok: ["rizeni"]
poradi: 1
editor: source
aliases: 
  - zadani-ukolu
  - zadani-analytickeho-ukolu
---

# O co jde a k čemu to je

Zde najdete postup, jak díky lepšímu zadávání analytického úkolu zvýšit využitelnost výstupů, zvýšit jejich kvalitu a dlouhodobě uspořit čas. 

I pokud samotné zadání a přebrání úkolu zabere trochu času navíc, nejspíš se to vrátí v kvalitě a menším plýtvání času na dělání nesprávných věcí. 

Proces zadávání analytických úkolů bývá zatížený několika problémy:

1. Zadavatelé analýzy už přicházejí s tím, jaké chtějí řešení, místo toho aby se zaměřovali na kvalitní definici problému. 
2. Proces zadání probíhá tichou poštou: "paní ředitelka mi říkala, že by ji zajímalo X, můžete se na to podívat?" Chybí prostor zjistit, co je skutečná otázka, motivace a zamýšlené využití výstupu.
3. Adresáti úkolu mají tendenci začít hned přemýšlet, jak úkol vyřešit, než se ptát po tom, jaká je skutečně otázka a k čemu bude odpověď.

# Sebediagnostika: je to pro mě?

Tento návod je hlavně pro analytiky a analytické týmy, především pak pro ty, kteří pracují v "transakčním" módu, tj. často reagují na ad hoc poptávky nějakého uživatele jejich výstupů, např. vedení organizace nebo věcného útvaru.

Návod by se vám mohl hodit především tehdy, když platí některé z následujících tvrzení:

- Často dostávám analytické úkoly
- Adresáti analytických výstupů mají pocit, že nedostávají to, co poptali, vrací se s dodatečnými otázkami atd.
- Analýzy nemají dopad na rozhodování, které od nich očekáváte
- Je poptáváno už definované řešení/výstup místo toho, aby se definoval problém nebo otázka, který je potřeba vyřešit 

:::{.aside}
<br>
:::

:::{.strip .page-columns .page-full}

# Jak na to

## 1. Vyjasněte otázku a účel

Začněte tím, že zadavateli vysvětlíte, že s analýzou musíme začít právě skrze definici problému.

K tomu pomáhá postoj (a někdy i přímé vyslovení věty) *Neříkej mi, jaké chceš řešení, řekni mi, jaký máš problém.* To platí obzvláště u "datových" úkolů.

V komunikaci s klientem poptávajícím analytickou práci pak vyjasněte následující body:

  - Jakou otázku má úkol odpovědět? Jaký problém má adresovat?
  - Jaké předpokládá zadavatel využití? Co s výstupem udělá?
  - Jakými zdroji a daty vztahujícími se k danému problému zadavatel již disponuje?
  - Ví zadavatel o nějaké existující analýze, zdrojích a literatuře k dané problematice? (Tím nezkoušíte ani se nezbavujete své role, ale zjišťujete, na co podle zadavatele můžete navázat)
  - Kdo další by analýzu kromě zadavatele mohl využít? 
  
Pokud toto není možné osobně, jde to i před dokumenty, např.:

- můžete v reakci na obdrženou poptávku sepsat krátký záměr analýzy, ve kterém vysvětlíte, jak úkol chápete, popř. navrhnete varianty, požádáte o potvrzení, a položíte doplňující otázky
- totéž můžete udělat v předpřipravené šabloně záměru analýzy
  
## 2. Vyjasněte kýžený výstup

Po vydefinování problému se potřebujete dobrat parametry práce a vykomunikovat se zadavatelem následující:  

  - Forma výstupu (můžete se ptát na představy, ale ještě lépe navrhnout podle odpovědí na předchozí body)
  - Termíny
  - Rozsah
  - Bude v průběhu tvorby výstupu možnost konzultací a průběžné zpětné vazby?
  
## 3. Ptejte se na zpětnou vazbu

Zeptejte se adresáta, jestli vaše práce splnila jeho potřebu.

Proberte s adresátem a sami zreflektujte, jestli proces zadání úkolu pomohl a jak ho zlepšit.

:::

# Na co si dát pozor aneb tipy & triky

Zkušenosti z projektu PANK i dalších kolegů a kolegyň z veřejné správy ukazují, že analytický úkol je často **zadán s de facto již stanoveným výstupem** (např. "Vypracujte analýzu vztahu socio-ekonomického zázemí a výkonu ve vzdělávání"). Přitom účelem analytické práce je často zodpovězení otázky či adresování problému ("co je příčinou nižších výsledků ve vzdělávání v daném kraji"). Analytici a analytičky by se měli snažit dobrat zadání úkolu na tétu úrovni. 

> Může pomoct věta typu: "Vaším úkolem je zkusit vyjádřit, co chcete vědět (jaký problém řešíte), můj úkol je přijít na to, jak otázku zodpovědět (problém vyřešit). Můžu vám pomoct tu otázku specifikovat?".

Jakkoli můžou pomoct postupy a nástroje (výše), **zásadní jsou funkční dlouhodobé vztahy s nejčastějšími zadavateli** analytické práce (kterých bývá na ministerstvu omezené množství). Ty pak povedou i ke sladění vzájemných očekávání v kontextu zadávání analytických úkolů, kdy nebude nutné výše zmíněné základní principy opakovat a vyjasňovat. Na začátku tedy vysvětlujte, proč k zadání úkolu přistupujete takto a co to komu přinese. 

Právě v těchto dlouhodobých spoluprácích může být nápomocné připravit **šablonu** pro zadávání analytických úkolů. Ta by měla sloužit jako základní osnova úkolu a pokrývat otázku/definici problému, deadliny, existující zdroje, případně potencionální uživatele koncového výstupu. Časem se vám může podařit vaše partnery **na tento způsob uvažování navyknout** - dobré kladení otázek je ostatně součástí výbavy pro práci s poznatky na straně klientů a zadavatelů analytické práce.

Takový postup pomůže i v případě, že analytický úkol řešíte např. **veřejnou zakázkou**. Ukazuje se totiž, že zadávací dokumentace není dobrý podklad pro vyjasňování cílů - právě proto některé evaluační jednotky pracují s dokumentem **záměru analýzy (evaluace)**, jehož účelem je vyjasnit cíle a otázky. O tom viz [Průvodce evaluátora](https://www.dotaceeu.cz/getmedia/3ce5f6b9-24cc-4ac1-80d9-9eb769203f5a/Pruvodce-evaluatora_final_202007.pdf.aspx) od Evaluační jednotky NOK.

# Další zdroje

[Evidence Transparency Framework](https://www.instituteforgovernment.org.uk/publications/evidence-transparency-framework)

[Aqua Book](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government)

[Using Evidence: A Practice Guide](https://media.nesta.org.uk/documents/Using_Research_Evidence_for_Success_-_A_Practice_Guide.pdf)

[Manager's guide to evaluation](https://www.betterevaluation.org/frameworks-guides/managers-guide-evaluation) 
